CREATE TABLE IF NOT EXISTS `dpn_dispatch_calls` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `call_id` int(11) NOT NULL,
  `case_id` varchar(80) DEFAULT NULL,
  `code` varchar(32) DEFAULT NULL,
  `title` varchar(120) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `departments` longtext DEFAULT NULL,
  `priority` int(11) DEFAULT 3,
  `status` varchar(32) DEFAULT 'pending',
  `location` varchar(160) DEFAULT NULL,
  `coords` longtext DEFAULT NULL,
  `caller_name` varchar(120) DEFAULT NULL,
  `caller_source` int(11) DEFAULT 0,
  `assigned_units` longtext DEFAULT NULL,
  `linked_reports` longtext DEFAULT NULL,
  `payload` longtext DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_call_id` (`call_id`),
  KEY `idx_case_id` (`case_id`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `dpn_dispatch_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `report_id` int(11) NOT NULL,
  `report_number` varchar(80) DEFAULT NULL,
  `case_id` varchar(80) DEFAULT NULL,
  `call_id` int(11) DEFAULT NULL,
  `type` varchar(64) DEFAULT 'incident',
  `title` varchar(160) DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `narrative` longtext DEFAULT NULL,
  `department` varchar(64) DEFAULT NULL,
  `departments` longtext DEFAULT NULL,
  `priority` int(11) DEFAULT 3,
  `status` varchar(64) DEFAULT 'draft',
  `location` varchar(180) DEFAULT NULL,
  `coords` longtext DEFAULT NULL,
  `reporting_unit` longtext DEFAULT NULL,
  `involved` longtext DEFAULT NULL,
  `tags` longtext DEFAULT NULL,
  `approvals` longtext DEFAULT NULL,
  `sealed` tinyint(1) DEFAULT 0,
  `confidential` tinyint(1) DEFAULT 0,
  `locked` tinyint(1) DEFAULT 0,
  `payload` longtext DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_report_number` (`report_number`),
  KEY `idx_case_id` (`case_id`),
  KEY `idx_call_id` (`call_id`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_department` (`department`),
  KEY `idx_sealed` (`sealed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
