local VERSION='10.0.0'
local damageControl, anesthesiaCommand, orCapacity = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateDamageControlPlanV10',function(target,procedure,team)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local item={id=uid('DCS'),target=tonumber(target),procedure=procedure,team=team or{},hemorrhageRate=twin.circulation.hemorrhageRateMlMin+twin.circulation.internalHemorrhageRateMlMin,clotStability=twin.circulation.clotStability,stages={'hemorrhage_control','contamination_control','temporary_closure','icu_resuscitation','definitive_repair'},status='planned',createdAt=os.time()};damageControl[item.id]=item;return true,item end)
exports('RecordAnesthesiaCommandV10',function(caseId,event,data,actor)local item=anesthesiaCommand[tostring(caseId)]or{id=uid('AN10'),caseId=caseId,events={}};item.events[#item.events+1]={event=event,data=data or{},actor=actor,at=os.time()};item.updatedAt=os.time();anesthesiaCommand[tostring(caseId)]=item;return true,item end)
exports('ForecastORCapacityV10',function(rooms,cases,staff)local available=tonumber(rooms and rooms.available)or 0;local demand=#(cases or{});local staffFactor=(tonumber(staff and staff.available)or 1)/math.max(1,tonumber(staff and staff.required)or 1);local item={id=uid('ORCAP'),available=available,demand=demand,staffFactor=staffFactor,status=demand>available*staffFactor and'over_capacity'or'available',createdAt=os.time()};orCapacity[item.id]=item;return item end)
exports('GetV10SurgeryBoard',function()return{version=VERSION,damageControl=damageControl,anesthesiaCommand=anesthesiaCommand,orCapacity=orCapacity,generatedAt=os.time()}end)
CreateThread(function()Wait(7200);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-surgery',VERSION,{'damage_control_surgery','anesthesia_command','or_capacity_forecast','coagulopathy_planning'})end);print('[dpn-medical-surgery] v10 damage-control surgery and OR command active')end)
