local VERSION='11.0.0'
local perioperative, executionPlans, checkpoints, outcomes = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreatePerioperativeDigitalTwinV11',function(target,procedure,team)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local risk=math.min(100,twin.v11.autonomousRisk*.55+(100-twin.microcirculation.endothelialIntegrity)*.2+twin.deviceSafety.infectionRisk*.15+twin.recovery.frailty*.2);local item={id=uid('PERI11'),target=tonumber(target),procedure=procedure,team=team or{},operativeRisk=math.floor(risk),bloodRequirement=(twin.circulation.hemorrhageRateMlMin+twin.circulation.internalHemorrhageRateMlMin)>=30 and'massive_transfusion_ready'or'type_and_screen',postOpLevel=twin.v11.predictedLevelOfCare,createdAt=os.time()};perioperative[item.id]=item;return true,item end)
exports('CreateORExecutionPlanV11',function(perioperativeId,room,actor)local twin=perioperative[tostring(perioperativeId)];if not twin then return false,'Perioperative twin not found.'end;local item={id=uid('OR11'),perioperativeId=perioperativeId,room=room,actor=actor,status='ready',checkpoints={'briefing','anesthesia_ready','antibiotic_time_out','incision','critical_view','counts','closure','handoff'},completed={},createdAt=os.time()};executionPlans[item.id]=item;return true,item end)
exports('RecordSurgicalCheckpointV11',function(planId,checkpoint,actor,data)local plan=executionPlans[tostring(planId)];if not plan then return false,'OR execution plan not found.'end;plan.completed[tostring(checkpoint)]={actor=actor,data=data or{},at=os.time()};checkpoints[#checkpoints+1]={planId=planId,checkpoint=checkpoint,actor=actor,at=os.time()};return true,plan end)
exports('RecordSurgicalOutcomeV11',function(planId,outcome,complications,actor)local item={id=uid('OUT11'),planId=planId,outcome=outcome,complications=complications or{},actor=actor,createdAt=os.time()};outcomes[item.id]=item;return true,item end)
exports('GetV11SurgeryBoard',function()return{version=VERSION,perioperative=perioperative,executionPlans=executionPlans,checkpoints=checkpoints,outcomes=outcomes,generatedAt=os.time()}end)
CreateThread(function()Wait(7200);print('[dpn-medical-surgery] v11 perioperative digital twin and OR execution control active')end)
