local VERSION='8.0.0'
local anesthesiaCharts, safetyCounts, complications = {}, {}, {}
local function uid(prefix) return ('%s-%s-%04d'):format(prefix,os.time(),math.random(0,9999)) end
exports('StartAnesthesiaChart',function(target,caseId,data,actor) data=type(data)=='table'and data or{};local chart={id=uid('ANES'),target=tonumber(target),caseId=caseId,asa=tonumber(data.asa)or 2,airway=data.airway or'normal',agents={},vitals={},fluids={},bloodLoss=0,status='induction',actor=actor,startedAt=os.time()};anesthesiaCharts[chart.id]=chart;return chart.id,chart end)
exports('RecordAnesthesiaEvent',function(chartId,event,data) local chart=anesthesiaCharts[tostring(chartId)];if not chart then return false end;chart.vitals[#chart.vitals+1]={event=event,data=data or{},at=os.time()};if event=='blood_loss'then chart.bloodLoss=chart.bloodLoss+(tonumber(data and data.ml)or 0)end;return true,chart end)
exports('CompleteSurgicalCount',function(caseId,category,expected,actual,actor) local item={id=uid('COUNT'),caseId=caseId,category=category,expected=tonumber(expected)or 0,actual=tonumber(actual)or 0,matched=tonumber(expected)==tonumber(actual),actor=actor,at=os.time()};safetyCounts[item.id]=item;if not item.matched then TriggerEvent('dpn-medical:surgery:countMismatch',item)end;return item.matched,item end)
exports('RecordSurgicalComplication',function(target,caseId,kind,severity,data,actor) local item={id=uid('COMP'),target=target,caseId=caseId,kind=kind,severity=severity or'moderate',data=data or{},actor=actor,at=os.time()};complications[item.id]=item;return item.id,item end)
exports('GetSurgeryV8Board',function()return{anesthesia=anesthesiaCharts,counts=safetyCounts,complications=complications,generatedAt=os.time()}end)
CreateThread(function()Wait(3000);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-surgery',VERSION,{'anesthesia_chart','surgical_counts','complication_registry','perioperative_safety'})end);print('[dpn-medical-surgery] v8 anesthesia and surgical safety operations active')end)
