local VERSION='10.0.0'
local commandPathways, criticalLoops, capacity = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateCommandImagingPathwayV10',function(target,question,available)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local modality=twin.v10.commandRisk>=80 and'bedside_ultrasound_then_ct'or twin.neuroCritical.cerebralOxygenRisk>=40 and'noncontrast_head_ct'or'ct_targeted';local item={id=uid('IMG10'),target=tonumber(target),question=question,modality=modality,available=available or{},priority=twin.v10.commandRisk>=70 and 1 or 2,transportRisk=twin.v10.commandRisk,createdAt=os.time()};commandPathways[item.id]=item;return true,item end)
exports('CreateCriticalResultLoopV10',function(target,finding,recipient)local item={id=uid('CRIT10'),target=tonumber(target),finding=finding,recipient=recipient,status='sent',sentAt=os.time(),acknowledged=false};criticalLoops[item.id]=item;return item.id,item end)
exports('AcknowledgeCriticalResultV10',function(id,actor)local item=criticalLoops[tostring(id)];if not item then return false,'Result not found.'end;item.acknowledged=true;item.acknowledgedBy=actor;item.acknowledgedAt=os.time();item.status='closed_loop';return true,item end)
exports('GetV10RadiologyBoard',function()return{version=VERSION,commandPathways=commandPathways,criticalLoops=criticalLoops,capacity=capacity,generatedAt=os.time()}end)
CreateThread(function()Wait(7300);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-radiology',VERSION,{'command_imaging','transport_risk','critical_result_loop','diagnostic_capacity'})end);print('[dpn-medical-radiology] v10 command imaging and critical-result closure active')end)
