local VERSION='11.0.0'
local pathways, worklists, criticalResults, discrepancies = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateAdaptiveImagingPathwayV11',function(target,question,options)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;options=type(options)=='table'and options or{};local modality=twin.v11.clinicalPriority=='immediate'and'ct_or_ultrasound_at_bedside'or options.preferred or'ct';local item={id=uid('IMG11'),target=tonumber(target),clinicalQuestion=question,modality=modality,transportRisk=twin.v11.autonomousRisk,contrastRisk=(twin.endocrine.endocrineRisk*.2+(twin.v8 and twin.v8.renal and twin.v8.renal.akiStage or 0)*20),priority=twin.v11.clinicalPriority,status='ordered',createdAt=os.time()};pathways[item.id]=item;return true,item end)
exports('PrioritizeImagingWorklistV11',function(studies)local rows={};for _,study in ipairs(studies or{})do local score=(tonumber(study.clinicalRisk)or 0)*.6+(tonumber(study.delayMinutes)or 0)*.4+(study.criticalQuestion and 25 or 0);study.priorityScore=math.floor(math.min(100,score));rows[#rows+1]=study end;table.sort(rows,function(a,b)return(a.priorityScore or 0)>(b.priorityScore or 0)end);local item={id=uid('WL11'),studies=rows,createdAt=os.time()};worklists[item.id]=item;return item end)
exports('CloseCriticalResultLoopV11',function(studyId,result,recipient,readBack)local item={id=uid('CR11'),studyId=studyId,result=result,recipient=recipient,readBack=readBack,status=readBack and'closed'or'awaiting_readback',createdAt=os.time()};criticalResults[item.id]=item;return true,item end)
exports('RecordDiagnosticDiscrepancyV11',function(studyId,preliminary,final,severity,reviewer)local item={id=uid('DISC11'),studyId=studyId,preliminary=preliminary,final=final,severity=severity,reviewer=reviewer,createdAt=os.time()};discrepancies[item.id]=item;return true,item end)
exports('GetV11RadiologyBoard',function()return{version=VERSION,pathways=pathways,worklists=worklists,criticalResults=criticalResults,discrepancies=discrepancies,generatedAt=os.time()}end)
CreateThread(function()Wait(7300);print('[dpn-medical-radiology] v11 adaptive imaging and closed-loop critical results active')end)
