local VERSION='10.0.0'
local toxicologyReviews, infusions, antidotePlans = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateToxicologyReviewV10',function(target,actor)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local item={id=uid('TOX10'),target=tonumber(target),actor=actor,toxicity=twin.toxicity,antidotes=twin.toxicity.antidotes,monitoring={},status='reviewed',createdAt=os.time()};if twin.toxicity.cardiotoxic>=25 then item.monitoring[#item.monitoring+1]='continuous_ecg'end;if twin.toxicity.opioid>=25 then item.monitoring[#item.monitoring+1]='capnography'end;toxicologyReviews[item.id]=item;return true,item end)
exports('CreateSmartInfusionV10',function(target,drug,rate,limits,actor)local minimum=tonumber(limits and limits.min)or 0;local maximum=tonumber(limits and limits.max)or 9999;rate=tonumber(rate)or 0;local item={id=uid('PUMP10'),target=tonumber(target),drug=drug,rate=rate,limits={min=minimum,max=maximum},actor=actor,status=(rate<minimum or rate>maximum)and'hard_stop'or'running',createdAt=os.time()};infusions[item.id]=item;return item.status=='running',item end)
exports('BuildAntidotePlanV10',function(target)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local item={id=uid('ANTI10'),target=tonumber(target),dominant=twin.toxicity.dominantToxidrome,antidotes=twin.toxicity.antidotes,burden=twin.toxicity.totalBurden,createdAt=os.time()};antidotePlans[item.id]=item;return true,item end)
exports('GetV10PharmacyBoard',function()return{version=VERSION,toxicologyReviews=toxicologyReviews,infusions=infusions,antidotePlans=antidotePlans,generatedAt=os.time()}end)
CreateThread(function()Wait(7400);print('[dpn-medical-pharmacy] v10 toxicology and smart-infusion safety active')end)
