local VERSION='11.0.0'
local transportPlans, telemedicine, handoffs, quality = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateAutonomousTransportPlanV11',function(target,unit,options)
 local ok,twin=core('GetV11Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;options=type(options)=='table'and options or{}
 local destination=twin.v11.predictedLevelOfCare=='resuscitation'and'trauma_resuscitation'or twin.v11.predictedLevelOfCare=='intensive_care'and'icu_capable_center'or options.defaultDestination or'nearest_emergency'
 local capabilities={};if twin.v10.predictedArrestMinutes>0 and twin.v10.predictedArrestMinutes<=15 then capabilities[#capabilities+1]='cardiac_arrest_capability'end;if twin.circulation.hemorrhageRateMlMin+twin.circulation.internalHemorrhageRateMlMin>=30 then capabilities[#capabilities+1]='blood_products'end;if twin.endocrine.endocrineRisk>=50 then capabilities[#capabilities+1]='metabolic_critical_care'end
 local item={id=uid('EMS11'),target=tonumber(target),unit=unit,destination=destination,priority=twin.v11.clinicalPriority,requiredCapabilities=capabilities,reassessmentSeconds=twin.v11.reassessmentIntervalSeconds,transportRisk=twin.v11.autonomousRisk,status='planned',createdAt=os.time()};transportPlans[item.id]=item;return true,item
end)
exports('StartTelemedicineConsultV11',function(target,unit,specialty,provider)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local item={id=uid('TEL11'),target=tonumber(target),unit=unit,specialty=specialty or'critical_care',provider=provider,status='connected',summary={risk=twin.v11.autonomousRisk,priority=twin.v11.clinicalPriority,recommendations=twin.recommendations},timeline={{event='connected',at=os.time()}},createdAt=os.time()};telemedicine[item.id]=item;return true,item end)
exports('RecordClosedLoopHandoffV11',function(target,fromUnit,toDepartment,actor)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local item={id=uid('HOF11'),target=tonumber(target),fromUnit=fromUnit,toDepartment=toDepartment,actor=actor,readBackRequired=true,readBackComplete=false,summary={priority=twin.v11.clinicalPriority,levelOfCare=twin.v11.predictedLevelOfCare,mortality=twin.v11.predictedMortality,careGaps=twin.recommendations},createdAt=os.time()};handoffs[item.id]=item;return true,item end)
exports('ScorePrehospitalQualityV11',function(missionId,metrics)local m=transportPlans[tostring(missionId)];metrics=type(metrics)=='table'and metrics or{};local score=100-math.max(0,(tonumber(metrics.sceneMinutes)or 0)-20)*2-math.max(0,(tonumber(metrics.handoffMinutes)or 0)-10)*2-(metrics.missedReassessment and 20 or 0);local item={id=uid('QA11'),missionId=missionId,score=math.max(0,math.min(100,score)),metrics=metrics,createdAt=os.time()};quality[item.id]=item;return true,item end)
exports('GetV11EMSBoard',function()return{version=VERSION,transportPlans=transportPlans,telemedicine=telemedicine,handoffs=handoffs,quality=quality,generatedAt=os.time()}end)
CreateThread(function()Wait(7000);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-ems',VERSION,{'autonomous_transport_planning','telemedicine','closed_loop_handoff','prehospital_quality'})end);print('[dpn-medical-ems] v11 autonomous transport, telemedicine and closed-loop handoff active')end)
