const app=document.getElementById('app');let state={dashboard:{players:[],cases:[],locations:[]}};
const $=id=>document.getElementById(id);function post(actionName,extra={}){fetch(`https://${GetParentResourceName()}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actionName,target:$('target')?.value,reason:$('reason')?.value,...extra})}).catch(()=>{})}
function closeUI(){fetch(`https://${GetParentResourceName()}/close`,{method:'POST',body:'{}'}).catch(()=>{});app.classList.add('hidden')}
window.addEventListener('message',e=>{const d=e.data||{};if(d.action==='open'){state.dashboard=d.dashboard||{};app.classList.remove('hidden');render()}if(d.action==='close')app.classList.add('hidden');if(d.action==='threatUpdate'){state.dashboard.threat=d.threat;state.dashboard.threatLabel=d.threatLabel;render()}if(d.action==='scanResult')out('Identity Scan',JSON.stringify(d.result,null,2));if(d.action==='vehicleScan')out('Vehicle Scan',JSON.stringify(d.result,null,2));if(d.action==='devResult')out(d.title||'Developer Result',d.text||'');if(d.action==='static'){const s=$('static');s.style.display='block';setTimeout(()=>s.style.display='none',d.duration||2500)}});
function out(title,text){$('output')&&($('output').textContent=`${title}\n${text}`);$('diag')&&($('diag').textContent=`${title}\n${text}`)}
function render(){let d=state.dashboard||{};$('playerCount').textContent=(d.players||[]).length;$('caseCount').textContent=(d.cases||[]).length;$('clock').textContent=d.serverTime||new Date().toLocaleTimeString();$('threatPill').textContent=(d.threatLabel||d.threat||'GREEN').toUpperCase();renderPlayers(d.players||[]);renderCases(d.cases||[]);renderPG(d.locations||[])}
function renderPlayers(players){let el=$('playersList');if(!el)return;el.innerHTML=players.map(p=>`<div class="row"><b>#${p.id}</b><span>${p.char||p.name}<br><small>${p.citizenid||''} | ${p.job||''} | bucket ${p.bucket??0}</small></span><small>Ping ${p.ping}</small><button onclick="setTarget(${p.id})">Target</button></div>`).join('')||'<p class="muted">No players loaded.</p>'}
function renderCases(cases){let el=$('caseList');if(!el)return;el.innerHTML=cases.map(c=>`<div class="row"><b>${c.threat}</b><span>${c.title}<br><small>${c.id} | ${c.owner}</small></span><small>${c.status}</small><button onclick="out('Case','${c.id}')">View</button></div>`).join('')||'<p class="muted">No cases yet.</p>'}
function renderPG(locs){let el=$('pgDestinations');if(!el)return;let defaults=['MIB HQ / MRPD','Pillbox','Sandy Federal','Paleto','Zancudo'];let arr=(locs.length?locs:defaults.map(label=>({label})));el.innerHTML=arr.map((l,i)=>`<button onclick="post('pg7x_destination',{index:${i+1}})">Open to ${l.label}</button>`).join('')}
window.setTarget=id=>{$('target').value=id;out('Target Selected',`Server ID ${id} selected.`)};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');$('pageTitle').textContent=b.textContent});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeUI()});$('closeBtn').onclick=closeUI;
document.body.addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b)return;const a=b.dataset.act;const map={scan:['scan'],cloak:['cloak'],cleanup:['cleanup'],armor:['armor'],revive:['revive'],freeze:['freeze'],goto_player:['goto_player'],bring:['bring'],spectate:['spectate'],lockdown:['lockdown'],wipe_scene:['wipe_scene'],kick:['kick'],vehicle_scan:['vehicle_scan'],cleanup_world:['cleanup_world'],resourceStatus:['resource_status'],pgAim:['pg7x_aim'],neuralAlpha:['advanced_neuralizer',{mode:'alpha'}],neuralBeta:['advanced_neuralizer',{mode:'beta'}],neuralGamma:['advanced_neuralizer',{mode:'gamma'}],neuralOmega:['advanced_neuralizer',{mode:'omega'}],neuralArea:['advanced_neuralizer',{mode:'area'}],healSelf:['admin_client',{clientAction:'heal'}],godmode:['admin_client',{clientAction:'godmode'}],invisible:['admin_client',{clientAction:'invisible'}],noclip:['admin_client',{clientAction:'noclip'}],repairVehicle:['admin_client',{clientAction:'repair_vehicle'}],cleanVehicle:['admin_client',{clientAction:'clean_vehicle'}],flipVehicle:['admin_client',{clientAction:'flip_vehicle'}],deleteVehicle:['admin_client',{clientAction:'delete_vehicle'}],copyCoords:['developer_client',{clientAction:'copy_coords'}],entityInspector:['developer_client',{clientAction:'entity_inspector'}],debugOverlay:['developer_client',{clientAction:'debug_overlay'}],pg1:['pg7x_destination',{index:1}],pg2:['pg7x_destination',{index:2}],pg5:['pg7x_destination',{index:5}]};
 if(a==='create_case')return post('create_case',{title:$('caseTitle').value||'Classified Incident',threat:$('caseThreat').value});
 if(a==='setBucket')return post('set_bucket',{bucket:prompt('Routing bucket ID','0')||0});
 if(a==='announce')return post('announce',{message:prompt('Announcement message','DPN MIB operation in progress.')||''});
 if(a==='weather')return post('weather',{weather:prompt('Weather type','CLEAR')||'CLEAR'});
 if(a==='time')return post('time',{hour:prompt('Hour','12')||12,minute:prompt('Minute','0')||0});
 if(a==='nuiReload')return location.reload(); if(a==='mibDebug')return out('Debug','Run /mibdebug in F8 for client details.');
 const m=map[a]; if(m)post(m[0],m[1]||{});
});
fetch(`https://${GetParentResourceName()}/ready`,{method:'POST',body:'{}'}).catch(()=>{});
setInterval(()=>{$('clock')&&($('clock').textContent=new Date().toLocaleTimeString())},1000);
