let incidents = {}, units = {}, bolos = {}, profile = {}, audit = [], config = {}, currentTab = 'dashboard';
const WORLD = { minX:-4000, maxX:4500, minY:-4500, maxY:8500 };
let satmapOk = false, satmapChecked = false;
function mapCfg(){ return config.liveMap || config.LiveMap || {}; }
function worldBounds(){ const c=mapCfg().WorldBounds || mapCfg().worldBounds || {}; return { minX:Number(c.minX ?? WORLD.minX), maxX:Number(c.maxX ?? WORLD.maxX), minY:Number(c.minY ?? WORLD.minY), maxY:Number(c.maxY ?? WORLD.maxY) }; }
const STATUS = ['available','busy','enroute','onscene','staged','transporting','offradio','out_of_service'];

function post(name, data = {}) {
  return fetch(`https://${GetParentResourceName()}/${name}`, { method:'POST', headers:{'Content-Type':'application/json; charset=UTF-8'}, body:JSON.stringify(data) }).catch(() => {});
}
function clean(text){ return String(text ?? '').replace(/[<>&"']/g, s => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[s])); }
function arr(obj){ return Object.values(obj || {}); }
function unitKey(u){ return u?.unitKey || (u?.citizenid ? `cid:${String(u.citizenid).toLowerCase().replace(/\s+/g,'')}` : `src:${u?.source || Math.random()}`); }
function safeId(id){ return String(id||'').replace(/[^a-zA-Z0-9:_-]/g,''); }
function validCoords(c){ if(!c) return null; const x=Number(c.x ?? c[0]), y=Number(c.y ?? c[1]), z=Number(c.z ?? c[2] ?? 0); if(!Number.isFinite(x)||!Number.isFinite(y)) return null; if(Math.abs(x)<0.01 && Math.abs(y)<0.01) return null; return {x,y,z}; }
function gtaToMap(c){ const w=worldBounds(); const left = ((c.x-w.minX)/(w.maxX-w.minX))*100; const top = 100-(((c.y-w.minY)/(w.maxY-w.minY))*100); return { left: Math.max(1, Math.min(99, left)), top: Math.max(1, Math.min(99, top)) }; }
function statusLabel(s){ return String(s||'available').replace(/_/g,' ').toUpperCase(); }
function closeUI(){ document.getElementById('app').classList.add('hidden'); post('close'); }
function fillStatuses(){ const sel=document.getElementById('unitStatus'); if(!sel) return; sel.innerHTML=(config.statuses||STATUS).map(s=>`<option value="${s}">${statusLabel(s)}</option>`).join(''); }
function setUnitStatus(status){ post('setUnitStatus',{status}); }
function dedupeUnits(raw){ const out={}; arr(raw).forEach(u=>{ if(!u) return; const k=unitKey(u); if(!out[k] || (u.lastSeen||0)>=(out[k].lastSeen||0)) out[k]=u; }); return out; }
function setTab(name, btn){ currentTab=name; document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active', b===btn || b.dataset.tab===name)); document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active-panel')); const target=document.getElementById(name==='dashboard'?'dashboard':`${name}Panel`); if(target) target.classList.add('active-panel'); if(name==='map') post('refreshSnapshot'); renderAll(); }

function filteredIncidents(){ const q=(document.getElementById('incidentSearch')?.value||'').toLowerCase(); const p=document.getElementById('priorityFilter')?.value||'all'; const s=document.getElementById('statusFilter')?.value||'active'; return arr(incidents).filter(i=>{ const active = !['resolved','archived','cancelled'].includes(i.status); if(s==='active'&&!active) return false; if(s!=='all'&&s!=='active'&&i.status!==s) return false; if(p!=='all'&&String(i.priority)!==p) return false; return !q || JSON.stringify(i).toLowerCase().includes(q); }).sort((a,b)=>(a.priority||9)-(b.priority||9)||(b.updatedAt||0)-(a.updatedAt||0)); }
function filteredUnits(){ const q=(document.getElementById('unitSearch')?.value||'').toLowerCase(); const a=document.getElementById('agencyFilter')?.value||'all'; return arr(units).filter(u=>(a==='all'||u.agency===a)&&(!q||JSON.stringify(u).toLowerCase().includes(q))).sort((a,b)=>String(a.callsign||'').localeCompare(String(b.callsign||''))); }

function incidentCard(i, compact=false){ const assigned=arr(i.assigned).map(u=>clean(u.callsign)).join(', ')||'Unassigned'; const agencies=(i.agencies||[]).map(clean).join(', ')||'None'; const c=validCoords(i.coords); const wp=c?`<button onclick='post("waypoint",${JSON.stringify({x:c.x,y:c.y})})'>Waypoint</button>`:''; const objectives=(i.objectives||[]).map(o=>`<label><input type="checkbox" ${o.done?'checked':''} onchange="post('toggleObjective',{incidentId:'${safeId(i.id)}',objectiveId:'${safeId(o.id)}'})"> ${clean(o.text)}</label>`).join(''); const people=[...(i.patients||[]).map(p=>'Patient: '+(p.name||p.condition||'Unknown')),...(i.suspects||[]).map(s=>'Suspect: '+(s.name||s.description||'Unknown')),...(i.vehicles||[]).map(v=>'Vehicle: '+(v.plate||v.model||'Unknown'))].slice(0,6).map(clean).join(' • '); const hist=(i.history||[]).slice(0,compact?0:8).map(h=>`<div>${new Date((h.time||0)*1000).toLocaleTimeString()} — ${clean(h.callsign)} — ${clean(h.action)} ${h.note?'— '+clean(h.note):''}</div>`).join(''); return `<div class="card priority-${i.priority}"><div class="card-head"><b>${clean(i.title)}</b><span class="badge p${i.priority}">P${i.priority}</span></div><div class="small">${clean(i.id)} | ${clean(i.status)} | ${clean(i.type)} | Postal ${clean(i.postal||'UNKNOWN')}</div>${compact?'':`<p>${clean(i.description)}</p>`}<div class="meta"><span>Agencies: ${agencies}</span><span>Assigned: ${assigned}</span><span>Commander: ${clean(i.sceneCommander||'Not Set')}</span><span>Hazard: ${clean(i.hazardLevel||'unknown')}</span></div>${people&&!compact?`<div class="intel-line">${people}</div>`:''}${!compact?`<div class="objectives">${objectives}</div><div class="timeline">${hist}</div>`:''}<div class="actions"><button onclick="post('assignSelf',{incidentId:'${safeId(i.id)}'})">Assign Me</button><button onclick="post('setStatus',{incidentId:'${safeId(i.id)}',status:'enroute'})">Enroute</button><button onclick="post('setStatus',{incidentId:'${safeId(i.id)}',status:'onscene'})">On Scene</button><button onclick="post('setStatus',{incidentId:'${safeId(i.id)}',status:'staged'})">Stage</button><button onclick="post('setStatus',{incidentId:'${safeId(i.id)}',status:'transporting'})">Transport</button><button onclick="post('setStatus',{incidentId:'${safeId(i.id)}',status:'resolved'})">Resolve</button>${wp}</div></div>`; }
function unitCard(u, compact=false){ const c=validCoords(u.coords); const stale=(Date.now()/1000-(u.lastSeen||0))>45; return `<div class="unit card ${clean(u.status)} ${stale?'stale':''}"><div class="card-head"><b>${clean(u.callsign||'Unit')} — ${clean(u.name||'Unknown')}</b><span class="badge">${statusLabel(u.status)}</span></div><div class="small">${clean(u.agencyLabel||u.agency)} | ${clean(u.job)} | Radio ${clean(u.radio||'OFF')} | ${c?'GPS OK':'NO GPS'}</div>${compact?'':`<div class="meta"><span>Assignment: ${clean(u.assignment||'None')}</span><span>${u.vehicle?clean(`${u.vehicle.model} ${u.vehicle.plate} ${u.vehicle.speed||0} MPH`):'No vehicle'}</span><span>Seen: ${u.lastSeen?new Date(u.lastSeen*1000).toLocaleTimeString():'Live'}</span></div>`}</div>`; }
function boloCard(b){ const tags=(b.tags||[]).map(t=>`<span class="tag">${clean(t)}</span>`).join(''); return `<div class="card bolo"><div class="card-head"><b>${clean(b.title)}</b><span class="badge p${b.priority||3}">P${b.priority||3}</span></div><div class="small">${clean(b.id)} | Plate ${clean(b.plate||'N/A')} | ${clean(b.vehicle||'Unknown vehicle')}</div><p>${clean(b.description)}</p><div class="meta"><span>Suspect: ${clean(b.suspect||'Unknown')}</span><span>Last Seen: ${clean(b.lastSeen||'Unknown')}</span><span>Threat: ${clean(b.threat||'Unknown')}</span></div>${tags}<div class="actions"><button onclick="post('archiveBolo',{boloId:'${safeId(b.id)}'})">Archive</button></div></div>`; }

function renderStats(){ const active=filteredIncidents(), live=filteredUnits(); const set=(id,v)=>{const e=document.getElementById(id); if(e)e.innerText=v}; set('statIncidents',active.length); set('statUnits',live.length); set('statPriority',active.filter(i=>Number(i.priority)===1).length); set('statAssigned',active.filter(i=>Object.keys(i.assigned||{}).length>0).length); set('statBolos',arr(bolos).filter(b=>b.active!==false).length); set('statMci',active.reduce((n,i)=>n+Number(i.triage?.red||0)+Number(i.triage?.yellow||0)+Number(i.triage?.green||0)+Number(i.triage?.black||0),0)); }
function renderMap(){
  const board=document.getElementById('mapBoard'), list=document.getElementById('mapList'); if(!board) return;
  const cfg=mapCfg();
  const img=cfg.ImageUrl || cfg.imageUrl || 'img/oulsen_satmap.png';
  const provider=(cfg.Provider || cfg.provider || 'oulsen_satmap').toString();
  const points=[];
  filteredIncidents().forEach(i=>{const c=validCoords(i.coords); if(c) points.push({kind:'incident',label:`P${i.priority}`,title:i.title,sub:i.id,coords:c,id:i.id,priority:i.priority});});
  filteredUnits().forEach(u=>{const c=validCoords(u.coords); if(c) points.push({kind:'unit',label:u.callsign||'U',title:u.name,sub:statusLabel(u.status),coords:c,id:unitKey(u),stale:(Date.now()/1000-(u.lastSeen||0))>45,agency:u.agency,status:u.status});});
  const dots=points.map(p=>{const m=gtaToMap(p.coords); return `<button class="map-dot ${p.kind} ${p.stale?'stale':''}" style="left:${m.left.toFixed(3)}%;top:${m.top.toFixed(3)}%" title="${clean(p.title)} | X ${Math.round(p.coords.x)} Y ${Math.round(p.coords.y)}" onclick='post("waypoint",${JSON.stringify({x:p.coords.x,y:p.coords.y})})'>${clean(String(p.label).slice(0,8))}<small>${clean(p.kind==='unit'?p.sub:p.id)}</small></button>`;}).join('');
  const statusText = `${provider.toUpperCase()} • ${points.length} LIVE POINTS • ${filteredUnits().filter(u=>validCoords(u.coords)).length}/${filteredUnits().length} UNITS GPS OK`;
  board.innerHTML = `<div class="oulsen-map-img" style="background-image:url('${clean(img)}')"></div><div class="oulsen-map-fallback"></div><div class="map-status-pill">${clean(statusText)}</div><div class="map-crosshair"></div>${dots}`;
  // Put fallback behind image. If image loads, browser paints it; if missing, fallback grid remains usable.
  const nogps=filteredUnits().filter(u=>!validCoords(u.coords));
  const stale=filteredUnits().filter(u=>validCoords(u.coords) && (Date.now()/1000-(u.lastSeen||0))>45);
  if(list) list.innerHTML=`<button onclick="post('refreshSnapshot')">Force GPS Refresh</button><button onclick="post('mapDebug')">Print Server GPS Debug</button><div class="map-row debug"><b>Provider</b><span>${clean(provider)}<br><code>${clean(img)}</code><br>Use exported oulsen_satmap PNG/JPG in html/img/oulsen_satmap.png.</span></div><h4>Live Units / Incidents</h4>`+
    points.map(p=>`<div class="map-row ${p.kind==='incident'?'inc':'ok'}"><b>${clean(p.label)}</b><span>${clean(p.title)} — ${clean(p.sub)}<br>X ${Math.round(p.coords.x)} Y ${Math.round(p.coords.y)} Z ${Math.round(p.coords.z||0)}</span></div>`).join('')+
    `<h4>No GPS Units</h4>`+(nogps.map(u=>`<div class="map-row warn"><b>${clean(u.callsign)}</b><span>${clean(u.name)} — no coords from client heartbeat yet. Have unit /unes or move.</span></div>`).join('')||'<p class="empty">None</p>')+
    `<h4>Stale GPS</h4>`+(stale.map(u=>`<div class="map-row warn"><b>${clean(u.callsign)}</b><span>${clean(u.name)} — last seen ${u.lastSeen?new Date(u.lastSeen*1000).toLocaleTimeString():'unknown'}</span></div>`).join('')||'<p class="empty">None</p>');
}
function renderAdvancedBoards(){ const active=filteredIncidents(); const set=(id,html)=>{const e=document.getElementById(id); if(e)e.innerHTML=html}; set('incidents',active.map(i=>incidentCard(i)).join('')||'<p class="empty">No incidents.</p>'); set('dashIncidents',active.slice(0,5).map(i=>incidentCard(i,true)).join('')||'<p class="empty">No active calls.</p>'); set('units',filteredUnits().map(u=>unitCard(u)).join('')||'<p class="empty">No units online.</p>'); set('dashUnits',filteredUnits().slice(0,8).map(u=>unitCard(u,true)).join('')||'<p class="empty">No units online.</p>'); set('bolos',arr(bolos).filter(b=>b.active!==false).sort((a,b)=>(a.priority||9)-(b.priority||9)).map(boloCard).join('')||'<p class="empty">No active BOLOs.</p>'); const risk=active.filter(i=>i.priority==1||i.hazardLevel==='high'||i.hazardLevel==='extreme'); set('riskBoard',risk.map(i=>incidentCard(i,true)).join('')||'<p class="empty">No major risk calls.</p>'); set('callQueue',active.map(i=>`<div class="queue-row"><b>P${i.priority} ${clean(i.title)}</b><span>${clean(i.status)} • ${clean((i.agencies||[]).join(', '))} • ${Object.keys(i.assigned||{}).length} units</span></div>`).join('')||'<p class="empty">Queue clear.</p>'); set('boloIntel',arr(bolos).filter(b=>b.active!==false).map(boloCard).join('')||'<p class="empty">No active intelligence bulletins.</p>'); set('audit',(audit||[]).slice(0,80).map(a=>`<div class="audit-row"><span>${new Date((a.time||0)*1000).toLocaleTimeString()}</span><span>${clean(a.callsign)}</span><span>${clean(a.action)}</span><span>${clean(a.target)}</span></div>`).join('')||'<p class="empty">No audit data.</p>'); }
function renderAll(){ renderStats(); renderMap(); renderAdvancedBoards(); }

function routeChecks(selector='.routeChecks input:checked'){ return [...document.querySelectorAll(selector)].map(x=>x.value); }
function createIncidentFromUI(){ const title=document.getElementById('newTitle').value || 'Emergency Incident'; const type=document.getElementById('newType').value; const priority=Number(document.getElementById('newPriority').value||3); const postal=document.getElementById('newPostal').value||'UNKNOWN'; const description=document.getElementById('newDescription').value||''; const hazardLevel=document.getElementById('newHazard')?.value||'unknown'; const callback=document.getElementById('newCallback')?.value||''; const caller=document.getElementById('newCaller')?.value||''; const staging=document.getElementById('newStaging')?.value||''; const crossStreet=document.getElementById('newCross')?.value||''; const tac=document.getElementById('newTac')?.value||''; const responseMode=document.getElementById('newMode')?.value||'normal'; const agencies=routeChecks(); const objectives=[`Establish command for ${title}`, 'Confirm exact location and access route', 'Update unit safety status'].map((text,i)=>({id:`LOCAL-${Date.now()}-${i}`,text,done:false})); post('createIncident',{title,type,priority,postal,description,hazardLevel,agencies,objectives,caller,callback,staging,crossStreet,tac,responseMode}); }
function createBolo(){ const data={ title:document.getElementById('boloTitle').value||'BOLO', plate:document.getElementById('boloPlate').value||'', vehicle:document.getElementById('boloVehicle').value||'', suspect:document.getElementById('boloSuspect').value||'', description:document.getElementById('boloDescription').value||'', priority:Number(document.getElementById('boloPriority')?.value||3), lastSeen:document.getElementById('boloLastSeen')?.value||'', threat:document.getElementById('boloThreat')?.value||'', tags:[document.getElementById('boloTag1')?.value,document.getElementById('boloTag2')?.value].filter(Boolean), riskIndicators:document.getElementById('boloRisk')?.value||'', notifyAgencies:(document.getElementById('boloNotify')?.value||'law').split(',').map(x=>x.trim()).filter(Boolean)}; post('createBolo',data); }
function requestSupport(){ post('requestSupport',{incidentId:document.getElementById('supportIncident').value, agencies:routeChecks('#supportPanel input[type=checkbox]:checked'), note:document.getElementById('supportNote').value}); }
function setCommander(){ post('setSceneCommander',{incidentId:document.getElementById('cmdIncident').value, commander:document.getElementById('cmdCommander').value}); }
function addNote(){ post('addIncidentNote',{incidentId:document.getElementById('cmdIncident').value, note:document.getElementById('incidentNote').value}); }
function addObjective(){ post('addObjective',{incidentId:document.getElementById('cmdIncident').value, text:document.getElementById('objectiveText').value}); }
function updateTriage(){ post('updateTriage',{incidentId:document.getElementById('triageIncident').value, red:document.getElementById('triRed').value, yellow:document.getElementById('triYellow').value, green:document.getElementById('triGreen').value, black:document.getElementById('triBlack').value}); }

window.addEventListener('message', ev=>{ const d=ev.data||{}; if(d.action==='open'||d.action==='snapshot'){ const p=d.payload||{}; incidents=p.incidents||incidents; units=dedupeUnits(p.units||units); bolos=p.bolos||bolos; profile=p.profile||profile; audit=p.audit||audit; config=p.config||config; document.getElementById('app').classList.remove('hidden'); const pr=document.getElementById('profile'); if(pr) pr.innerText=`${profile.callsign||'Unit'} • ${profile.agencyLabel||profile.agency||'Emergency Services'} • ${profile.name||''}`; fillStatuses(); renderAll(); } if(d.action==='incidentUpdated'){ incidents[d.incident.id]=d.incident; renderAll(); } if(d.action==='unitUpdated'){ units=dedupeUnits({...units,[unitKey(d.unit)]:d.unit}); renderAll(); } if(d.action==='unitRemoved'){ delete units[d.unitKey]; renderAll(); } if(d.action==='boloUpdated'){ bolos[d.bolo.id]=d.bolo; renderAll(); } });
setInterval(()=>{ if(!document.getElementById('app').classList.contains('hidden')) post('refreshSnapshot'); }, ((mapCfg().RefreshSeconds||mapCfg().refreshSeconds||5)*1000));
document.addEventListener('keyup',e=>{ if(e.key==='Escape') closeUI(); });
