local VERSION='11.0.0'
local eligibility, necessity, claims, appeals = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('EstimateCoverageV11',function(target,policy,services)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local total=0;for _,s in ipairs(services or{})do total=total+(tonumber(s.cost)or 0)end;local coverage=tonumber(policy and policy.coveragePercent)or 80;local item={id=uid('ELIG11'),target=tonumber(target),policy=policy or{},services=services or{},estimatedTotal=total,estimatedCovered=math.floor(total*coverage/100),patientEstimate=math.floor(total*(100-coverage)/100),clinicalPriority=twin.v11.clinicalPriority,createdAt=os.time()};eligibility[item.id]=item;return true,item end)
exports('CreateMedicalNecessityPacketV11',function(target,service,actor)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local item={id=uid('NEC11'),target=tonumber(target),service=service,actor=actor,evidence={risk=twin.v11.autonomousRisk,levelOfCare=twin.v11.predictedLevelOfCare,mortality=twin.v11.predictedMortality,recommendations=twin.recommendations},status='ready',createdAt=os.time()};necessity[item.id]=item;return true,item end)
exports('AdjudicateClaimV11',function(claimId,charges,policy,reviewer)local total=0;for _,c in ipairs(charges or{})do total=total+(tonumber(c.amount)or 0)end;local allowed=math.floor(total*(tonumber(policy and policy.allowedPercent)or 80)/100);local item={id=uid('CLM11'),claimId=claimId,total=total,allowed=allowed,patientResponsibility=total-allowed,reviewer=reviewer,status='adjudicated',createdAt=os.time()};claims[item.id]=item;return true,item end)
exports('CreateInsuranceAppealV11',function(claimId,reason,evidence,actor)local item={id=uid('APP11'),claimId=claimId,reason=reason,evidence=evidence or{},actor=actor,status='submitted',createdAt=os.time()};appeals[item.id]=item;return true,item end)
exports('GetV11InsuranceBoard',function()return{version=VERSION,eligibility=eligibility,necessity=necessity,claims=claims,appeals=appeals,generatedAt=os.time()}end)
CreateThread(function()Wait(7700);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-insurance',VERSION,{'coverage_estimation','medical_necessity','claim_adjudication','appeals'})end);print('[dpn-medical-insurance] v11 coverage, necessity and claim adjudication active')end)
