local VERSION='11.0.0'
local supplyPlans, reservations, forecasts, recalls = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
exports('CreateCriticalSupplyPlanV11',function(patientCount,acuityMix,inventory)local critical=tonumber(acuityMix and acuityMix.critical)or 0;local high=tonumber(acuityMix and acuityMix.high)or 0;local item={id=uid('SUP11'),patientCount=tonumber(patientCount)or 0,required={blood=critical*4,airwayKits=critical,ivKits=critical*2+high,traumaKits=critical+high,medicationKits=critical+math.ceil(high/2)},inventory=inventory or{},shortages={},createdAt=os.time()};for name,amount in pairs(item.required)do if(tonumber(item.inventory[name])or 0)<amount then item.shortages[#item.shortages+1]={item=name,required=amount,available=tonumber(item.inventory[name])or 0}end end;supplyPlans[item.id]=item;return true,item end)
exports('ReserveCareBundleV11',function(planId,items,location,actor)local item={id=uid('RES11'),planId=planId,items=items or{},location=location,actor=actor,status='reserved',createdAt=os.time()};reservations[item.id]=item;return true,item end)
exports('ForecastSupplyBurnRateV11',function(consumption,hours,stock)local rates={};local shortageHours={};for item,used in pairs(consumption or{})do local rate=(tonumber(used)or 0)/math.max(1,tonumber(hours)or 1);rates[item]=rate;shortageHours[item]=rate>0 and(tonumber(stock and stock[item])or 0)/rate or 999 end;local result={id=uid('BURN11'),rates=rates,shortageHours=shortageHours,createdAt=os.time()};forecasts[result.id]=result;return result end)
exports('CreateRecallActionV11',function(lot,item,locations,actor)local result={id=uid('RECALL11'),lot=lot,item=item,locations=locations or{},actor=actor,status='active',createdAt=os.time()};recalls[result.id]=result;return true,result end)
exports('GetV11InventoryBoard',function()return{version=VERSION,supplyPlans=supplyPlans,reservations=reservations,forecasts=forecasts,recalls=recalls,generatedAt=os.time()}end)
CreateThread(function()Wait(8600);print('[dpn-medical-inventory] v11 critical supply planning and burn-rate forecasting active')end)
