local VERSION='11.0.0'
local trajectories, readiness, milestones, homePlans = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateRecoveryTrajectoryV11',function(target,discipline,goals)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local item={id=uid('REH11'),target=tonumber(target),discipline=discipline or'multidisciplinary',goals=goals or{},rehabilitationNeed=twin.recovery.rehabilitationNeed,frailty=twin.recovery.frailty,predictedHours=twin.recovery.predictedRecoveryHours,status='active',createdAt=os.time()};trajectories[item.id]=item;return true,item end)
exports('EvaluateDischargeReadinessV11',function(target,environment,supports)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local supportScore=tonumber(supports and supports.score)or 50;local score=100-twin.recovery.dischargeBarrierScore*.7+twin.recovery.physiologicReserve*.3+supportScore*.2;local item={id=uid('DISCH11'),target=tonumber(target),score=math.floor(math.max(0,math.min(100,score))),ready=score>=70,environment=environment or{},supports=supports or{},barriers=twin.recovery.dischargeBarrierScore,createdAt=os.time()};readiness[item.id]=item;return true,item end)
exports('RecordFunctionalMilestoneV11',function(target,milestone,score,provider)local item={id=uid('MILE11'),target=tonumber(target),milestone=milestone,score=score,provider=provider,createdAt=os.time()};milestones[item.id]=item;return true,item end)
exports('CreateHomeRecoveryPlanV11',function(target,equipment,visits,actor)local item={id=uid('HOME11'),target=tonumber(target),equipment=equipment or{},visits=visits or{},actor=actor,status='planned',createdAt=os.time()};homePlans[item.id]=item;return true,item end)
exports('GetV11RehabBoard',function()return{version=VERSION,trajectories=trajectories,readiness=readiness,milestones=milestones,homePlans=homePlans,generatedAt=os.time()}end)
CreateThread(function()Wait(8400);print('[dpn-medical-rehab] v11 recovery trajectory and discharge readiness active')end)
