local VERSION='9.0.0'
local trajectories, readiness, milestones = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateRecoveryTrajectoryV9',function(target,baseline,goals)local ok,twin=core('GetV9Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local days=math.max(1,math.ceil((100-(twin.v9.recoveryProbability or 50))/4));local item={id=uid('REHAB'),target=tonumber(target),baseline=baseline or{},goals=goals or{},predictedDays=days,recoveryProbability=twin.v9.recoveryProbability,status='active',createdAt=os.time()};trajectories[item.id]=item;return true,item end)
exports('EvaluateHomeReadinessV9',function(target,assessment)local ok,twin=core('GetV9Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;assessment=type(assessment)=='table'and assessment or{};local score=(tonumber(assessment.mobility)or 0)*.35+(tonumber(assessment.selfCare)or 0)*.30+(tonumber(assessment.cognition)or 0)*.20+(tonumber(assessment.support)or 0)*.15;local item={id=uid('HOME'),target=tonumber(target),score=math.floor(score),ready=score>=75 and twin.v9.adaptiveRisk<35,barriers={},createdAt=os.time()};if score<75 then item.barriers={'functional_or_support_barrier'}end;readiness[item.id]=item;return true,item end)
exports('RecordFunctionalMilestoneV9',function(target,trajectoryId,milestone,score,actor)local item={id=uid('MILE'),target=tonumber(target),trajectoryId=trajectoryId,milestone=milestone,score=score,actor=actor,createdAt=os.time()};milestones[item.id]=item;return true,item end)
exports('GetV9RehabBoard',function()return{version=VERSION,trajectories=trajectories,readiness=readiness,milestones=milestones,generatedAt=os.time()}end)
CreateThread(function()Wait(6400);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-rehab',VERSION,{'recovery_trajectory','home_readiness','functional_milestones','adaptive_discharge'})end);print('[dpn-medical-rehab] v9 recovery trajectory and home-readiness planning active')end)
