local VERSION=GetResourceMetadata(GetCurrentResourceName(),'version',0) or 'unknown'
local reports={}
local function permitted(src)if src==0 then return true end;if IsPlayerAceAllowed(src,'dpn.medical.admin')then return true end;local ok,c=pcall(function()return exports['qb-core']:GetCoreObject()end);return ok and c and c.Functions and c.Functions.HasPermission and(c.Functions.HasPermission(src,'admin')or c.Functions.HasPermission(src,'god'))or false end
local function call(resource,name,...)local args=table.pack(...);local ok,a,b=pcall(function()local p=exports[resource];local fn=p and p[name];if type(fn)~='function'then error(('missing export %s:%s'):format(resource,name))end;return fn(p,table.unpack(args,1,args.n))end);return ok,a,b end
local tests={
{'dpn-medical-core','RunV14SelfTest'},{'dpn-medical-ems','GetV14EMSBoard'},{'dpn-medical-hospital','GetV14HospitalBoard'},{'dpn-medical-surgery','GetV14SurgeryBoard'},{'dpn-medical-radiology','GetV14RadiologyBoard'},{'dpn-medical-pharmacy','GetV14PharmacyBoard'},{'dpn-medical-records','GetV14RecordsBoard'},{'dpn-medical-coroner','GetV14CoronerBoard'},{'dpn-medical-insurance','GetV14InsuranceBoard'},{'dpn-medical-training','GetV14TrainingBoard'},{'dpn-medical-disease','GetV14DiseaseBoard'},{'dpn-medical-ambulance','GetV14AmbulanceBoard'},{'dpn-medical-ai','GetV14AIBoard'},{'dpn-medical-dispatch','GetV14DispatchBoard'},{'dpn-medical-icu','GetV14ICUBoard'},{'dpn-medical-rehab','GetV14RehabBoard'},{'dpn-medical-lifepak','GetV14LifepakBoard'},{'dpn-medical-inventory','GetV14InventoryBoard'},{'dpn-medical-billing-plus','GetV14BillingBoard'} }
exports('RunTraumaNetworkTestV14',function(actor)local report={id=('V14TEST-%s-%04d'):format(os.time(),math.random(0,9999)),actor=actor,modules={},passed=0,failed=0,startedAt=os.time()};for _,t in ipairs(tests)do local resource,name=t[1],t[2];local started=GetResourceState(resource)=='started';local ok,result,detail=false,nil,nil;if started then ok,result,detail=call(resource,name)end;local pass=started and ok and type(result)=='table'and result.passed~=false;report.modules[#report.modules+1]={resource=resource,exportName=name,started=started,passed=pass,version=GetResourceMetadata(resource,'version',0),detail=pass and nil or tostring(detail or result)};if pass then report.passed=report.passed+1 else report.failed=report.failed+1 end end;report.completedAt=os.time();report.success=report.failed==0;reports[report.id]=report;return report end)
exports('GetTraumaNetworkOperationsV14',function()local ok,data=call('dpn-medical-core','GetV14OperationalDashboard');return ok and type(data)=='table'and data or{version=VERSION,patients={},traumaOne=0,airwayThreat=0,occultBleed=0,compartmentRisk=0,activeMTP=0}end)
exports('GetTraumaNetworkTestReportsV14',function()return reports end)
RegisterCommand('medv14systemtest',function(src)if not permitted(src)then return end;local report=exports['dpn-medical-admin-tools']:RunTraumaNetworkTestV14(src);local msg=('v14 trauma network test: %s passed, %s failed, success=%s'):format(report.passed,report.failed,tostring(report.success));if src==0 then print(msg)else TriggerClientEvent('chat:addMessage',src,{args={'DPN Medical v14',msg}})end end,false)
CreateThread(function()Wait(9800);print(('[dpn-medical-admin-tools] %s trauma-operations dashboard and validation center active'):format(VERSION))end)
