local VERSION='14.0.0'
local traumaSessions, activations, checklists, mtpCases, transfers, events, trends = {}, {}, {}, {}, {}, {}, {}
local function now() return os.time() end
local function uid(prefix,target)return('%s-%s-%s-%04d'):format(prefix,now(),tostring(target or 0),math.random(0,9999))end
local function encode(value)local ok,data=pcall(json.encode,value);return ok and data or'{}'end
local function player(target)local ok,core=pcall(function()return exports['qb-core']:GetCoreObject()end);if not ok or not core or not core.Functions then return nil end;local ok2,p=pcall(function()return core.Functions.GetPlayer(tonumber(target))end);return ok2 and p or nil end
local function cid(target)local p=player(target);return p and p.PlayerData and p.PlayerData.citizenid or('source:%s'):format(tostring(target))end
local function stateFor(target)if not DPNMedicalServer or not DPNMedicalServer.EnsureState then return nil end;return DPNMedicalServer.EnsureState(tonumber(target))end
local function commit(target,state,eventType,data)if not DPNMedicalServer or not DPNMedicalServer.Commit then return false end;local _,pcid=DPNMedicalServer.EnsureState(tonumber(target));if not pcid then return false end;DPNMedicalServer.Commit(tonumber(target),pcid,state,eventType,data or{});return true end
local function persist(sql,params,update)CreateThread(function()pcall(function()if update then MySQL.update.await(sql,params)else MySQL.insert.await(sql,params)end end)end)end
local function count(t)local n=0;for _ in pairs(type(t)=='table'and t or{})do n=n+1 end;return n end
local function event(target,eventType,data,actor)local item={id=uid('EV14',target),target=tonumber(target),patientCid=target and cid(target)or nil,eventType=tostring(eventType),data=data or{},actor=tostring(actor or'system'),at=now()};events[target or 0]=events[target or 0]or{};table.insert(events[target or 0],1,item);while#events[target or 0]>400 do table.remove(events[target or 0])end;persist('INSERT INTO dpn_medical_v14_events (event_id,patient_cid,event_type,event_data,actor) VALUES (?,?,?,?,?)',{item.id,item.patientCid,item.eventType,encode(item.data),item.actor});return item end
local function trend(target,state,source)local point=DPN_MED.BuildV14TrendPoint(state);point.id=uid('TR14',target);point.source=source or'state_change';trends[target]=trends[target]or{};table.insert(trends[target],1,point);while#trends[target]>360 do table.remove(trends[target])end;return point end

exports('GetV14Twin',function(target)local s=stateFor(target);return s and DPN_MED.BuildV14Twin(s)or nil end)
exports('ForecastTreatmentV14',function(target,intervention)local s=stateFor(target);if not s then return false,'Patient not found.'end;return true,DPN_MED.ForecastTreatmentV14(s,intervention)end)
exports('CompareTraumaDestinationsV14',function(target,destinations)local s=stateFor(target);if not s then return false,'Patient not found.'end;return true,DPN_MED.CompareTraumaDestinationsV14(s,destinations)end)

exports('StartTraumaEvolutionV14',function(target,scenario,options,actor)
 target=tonumber(target);local s=stateFor(target);if not s then return false,'Patient not found.'end;options=type(options)=='table'and options or{};local item={id=uid('CLOCK14',target),target=target,patientCid=cid(target),scenario=tostring(scenario or'trauma'),status='active',actor=tostring(actor or'system'),elapsedMinutes=0,speed=math.max(.25,math.min(10,tonumber(options.speed)or 1)),applyToLive=options.applyToLive==true,history={},startedAt=now()};traumaSessions[item.id]=item;persist('INSERT INTO dpn_medical_v14_trauma_sessions (session_id,patient_cid,scenario,status,session_data,created_by) VALUES (?,?,?,?,?,?)',{item.id,item.patientCid,item.scenario,item.status,encode(item),item.actor});event(target,'trauma_evolution_started',{sessionId=item.id,scenario=item.scenario},item.actor);return item.id,item
end)
exports('AdvanceTraumaEvolutionV14',function(sessionId,minutes)
 local item=traumaSessions[tostring(sessionId)];if not item or item.status~='active'then return false,'Active trauma session not found.'end;minutes=math.max(1,math.min(120,tonumber(minutes)or 5));local s=stateFor(item.target);if not s then return false,'Patient not found.'end;item.elapsedMinutes=item.elapsedMinutes+minutes*item.speed;s.flags=s.flags or{};s.flags.traumaElapsedMinutes=(tonumber(s.flags.traumaElapsedMinutes)or 0)+minutes*item.speed
 local twin=DPN_MED.BuildV14Twin(s);local drift=(twin.traumaV14.externalHemorrhageRate*.012+twin.traumaV14.occultHemorrhageRisk*.008+twin.airwayV14.ventilationFailureRisk*.006)*minutes*item.speed
 s.vitals.blood=math.max(0,(tonumber(s.vitals.blood)or 5000)-drift*10);s.status.shock=math.min(100,(tonumber(s.status.shock)or 0)+drift*.28);DPN_MED.CalculateV14Metrics(s)
 if item.applyToLive then commit(item.target,s,'v14_trauma_evolution',{sessionId=item.id,minutes=minutes})end;local point=DPN_MED.BuildV14TrendPoint(s);point.elapsed=item.elapsedMinutes;item.history[#item.history+1]=point;if#item.history>240 then table.remove(item.history,1)end;persist('UPDATE dpn_medical_v14_trauma_sessions SET status=?,session_data=?,updated_at=NOW() WHERE session_id=?',{item.status,encode(item),item.id},true);return true,item
end)
exports('StopTraumaEvolutionV14',function(sessionId,actor)local item=traumaSessions[tostring(sessionId)];if not item then return false,'Trauma session not found.'end;item.status='stopped';item.stoppedBy=tostring(actor or'system');item.stoppedAt=now();persist('UPDATE dpn_medical_v14_trauma_sessions SET status=?,session_data=?,updated_at=NOW() WHERE session_id=?',{item.status,encode(item),item.id},true);return true,item end)
exports('GetTraumaEvolutionV14',function(id)return traumaSessions[tostring(id)]end)

exports('CreateTraumaActivationV14',function(target,location,actor)
 target=tonumber(target);local s=stateFor(target);if not s then return false,'Patient not found.'end;local twin=DPN_MED.BuildV14Twin(s);local item={id=uid('TRAUMA14',target),target=target,patientCid=cid(target),location=location,tier=twin.v14.traumaTier,risk=twin.v14.traumaCommandRisk,destination=twin.v14.recommendedDestination,team=twin.v14.recommendedTeam,status='active',actor=tostring(actor or'system'),createdAt=now()};activations[item.id]=item;persist('INSERT INTO dpn_medical_v14_activations (activation_id,patient_cid,tier,status,activation_data,created_by) VALUES (?,?,?,?,?,?)',{item.id,item.patientCid,item.tier,item.status,encode(item),item.actor});TriggerEvent('dpn-medical:server:v14TraumaActivation',item);TriggerEvent('dpn-medical-dispatch:server:v14TraumaActivation',item);event(target,'trauma_activation',{activationId=item.id,tier=item.tier},item.actor);return true,item
end)
exports('UpdateTraumaActivationV14',function(id,status,actor)local item=activations[tostring(id)];if not item then return false,'Activation not found.'end;item.status=tostring(status or item.status);item.updatedBy=tostring(actor or'system');item.updatedAt=now();persist('UPDATE dpn_medical_v14_activations SET status=?,activation_data=?,updated_at=NOW() WHERE activation_id=?',{item.status,encode(item),item.id},true);return true,item end)
exports('GetTraumaActivationsV14',function()return activations end)

exports('CreateProcedureChecklistV14',function(target,procedure,actor)
 target=tonumber(target);local s=stateFor(target);if not s then return false,'Patient not found.'end;local twin=DPN_MED.BuildV14Twin(s);local item={id=uid('CHK14',target),target=target,patientCid=cid(target),procedure=tostring(procedure or'damage_control'),status='draft',actor=tostring(actor or'system'),risk=twin.procedureV14.anesthesiaRisk,readiness=twin.procedureV14.readiness,steps={{id='identity',label='Confirm patient identity',status='pending'},{id='procedure',label='Confirm procedure and site',status='pending'},{id='consent',label='Confirm consent or emergency authority',status='pending'},{id='airway',label='Confirm airway and rescue plan',status='pending'},{id='blood',label='Confirm blood products and hemorrhage plan',status='pending'},{id='monitoring',label='Confirm monitoring and equipment',status='pending'},{id='briefing',label='Complete multidisciplinary briefing',status='pending'}},createdAt=now()};checklists[item.id]=item;persist('INSERT INTO dpn_medical_v14_checklists (checklist_id,patient_cid,procedure_name,status,checklist_data,created_by) VALUES (?,?,?,?,?,?)',{item.id,item.patientCid,item.procedure,item.status,encode(item),item.actor});event(target,'procedure_checklist_created',{checklistId=item.id,procedure=item.procedure},item.actor);return item.id,item
end)
exports('CompleteProcedureChecklistStepV14',function(checklistId,stepId,actor,evidence)local item=checklists[tostring(checklistId)];if not item then return false,'Checklist not found.'end;local found;for _,step in ipairs(item.steps)do if step.id==tostring(stepId)then found=step break end end;if not found then return false,'Checklist step not found.'end;found.status='complete';found.completedBy=tostring(actor or'system');found.completedAt=now();found.evidence=evidence;local complete=true;for _,step in ipairs(item.steps)do if step.status~='complete'then complete=false break end end;item.status=complete and'complete'or'active';persist('UPDATE dpn_medical_v14_checklists SET status=?,checklist_data=?,updated_at=NOW() WHERE checklist_id=?',{item.status,encode(item),item.id},true);return true,item end)
exports('GetProcedureChecklistsV14',function(target)local out={};for _,item in pairs(checklists)do if not target or tonumber(item.target)==tonumber(target)then out[item.id]=item end end;return out end)

exports('ActivateMassiveTransfusionV14',function(target,location,actor)
 target=tonumber(target);local s=stateFor(target);if not s then return false,'Patient not found.'end;local item={id=uid('MTP14',target),target=target,patientCid=cid(target),location=tostring(location or'main_blood_bank'),status='active',actor=tostring(actor or'system'),products={packedCells=0,plasma=0,platelets=0,cryo=0,calcium=0},targetRatio='1:1:1',startedAt=now()};mtpCases[item.id]=item;persist('INSERT INTO dpn_medical_v14_mtp (mtp_id,patient_cid,status,mtp_data,created_by) VALUES (?,?,?,?,?)',{item.id,item.patientCid,item.status,encode(item),item.actor});event(target,'mtp_activated',{mtpId=item.id},item.actor);TriggerEvent('dpn-medical-inventory:server:v14MTPActivated',item);return true,item
end)
exports('RecordBloodProductV14',function(mtpId,product,amount,actor)local item=mtpCases[tostring(mtpId)];if not item then return false,'MTP case not found.'end;product=tostring(product or'packedCells');amount=math.max(0,tonumber(amount)or 0);item.products[product]=(tonumber(item.products[product])or 0)+amount;item.updatedAt=now();item.updatedBy=tostring(actor or'system');local s=stateFor(item.target);if s then s.v14TransfusionLog=s.v14TransfusionLog or{};s.v14TransfusionLog[#s.v14TransfusionLog+1]={product=product,amount=amount,actor=actor,at=now()};DPN_MED.CalculateV14Metrics(s);commit(item.target,s,'v14_blood_product',{mtpId=item.id,product=product,amount=amount})end;persist('UPDATE dpn_medical_v14_mtp SET mtp_data=?,updated_at=NOW() WHERE mtp_id=?',{encode(item),item.id},true);return true,item end)
exports('CloseMassiveTransfusionV14',function(mtpId,actor)local item=mtpCases[tostring(mtpId)];if not item then return false,'MTP case not found.'end;item.status='closed';item.closedBy=tostring(actor or'system');item.closedAt=now();persist('UPDATE dpn_medical_v14_mtp SET status=?,mtp_data=?,updated_at=NOW() WHERE mtp_id=?',{item.status,encode(item),item.id},true);return true,item end)
exports('GetMassiveTransfusionCasesV14',function()return mtpCases end)

exports('CreateCriticalTransferPlanV14',function(target,destinations,actor)
 target=tonumber(target);local s=stateFor(target);if not s then return false,'Patient not found.'end;local ranked=DPN_MED.CompareTraumaDestinationsV14(s,destinations);local item={id=uid('XFER14',target),target=target,patientCid=cid(target),actor=tostring(actor or'system'),status='planned',rankedDestinations=ranked,selected=ranked[1]and ranked[1].id or nil,createdAt=now()};transfers[item.id]=item;persist('INSERT INTO dpn_medical_v14_transfers (transfer_id,patient_cid,status,transfer_data,created_by) VALUES (?,?,?,?,?)',{item.id,item.patientCid,item.status,encode(item),item.actor});event(target,'critical_transfer_planned',{transferId=item.id,selected=item.selected},item.actor);return item.id,item
end)
exports('GetCriticalTransferPlansV14',function()return transfers end)
exports('GetV14Events',function(target,limit)local rows=events[tonumber(target)]or{};local out={};for i=1,math.min(#rows,tonumber(limit)or 50)do out[#out+1]=rows[i]end;return out end)

exports('GetV14OperationalDashboard',function()
 local patients,traumaOne,airwayThreat,occultBleed,compartment,mtpActive={},0,0,0,0,0
 for _,sid in ipairs(GetPlayers()or{})do local target=tonumber(sid);local s=stateFor(target);if s then local twin=DPN_MED.BuildV14Twin(s);if twin.v14.traumaTier=='trauma_one'then traumaOne=traumaOne+1 end;if twin.airwayV14.airwayProtection<55 then airwayThreat=airwayThreat+1 end;if twin.traumaV14.occultHemorrhageRisk>=55 then occultBleed=occultBleed+1 end;if twin.traumaV14.compartmentSyndromeRisk>=50 then compartment=compartment+1 end;patients[#patients+1]={id=target,citizenid=cid(target),twin=twin,activeSession=false,checklistCount=0}end end
 for _,item in pairs(traumaSessions)do if item.status=='active'then for _,p in ipairs(patients)do if p.id==item.target then p.activeSession=true end end end end
 for _,item in pairs(checklists)do for _,p in ipairs(patients)do if p.id==item.target then p.checklistCount=p.checklistCount+1 end end end
 for _,item in pairs(mtpCases)do if item.status=='active'then mtpActive=mtpActive+1 end end
 table.sort(patients,function(a,b)return(a.twin.v14.traumaCommandRisk or 0)>(b.twin.v14.traumaCommandRisk or 0)end)
 return{version=VERSION,generatedAt=now(),patients=patients,traumaOne=traumaOne,airwayThreat=airwayThreat,occultBleed=occultBleed,compartmentRisk=compartment,activeMTP=mtpActive,activeSessions=count(traumaSessions),activations=count(activations),checklists=count(checklists),transferPlans=count(transfers)}
end)
exports('RunV14SelfTest',function()local shared=DPN_MED.RunV14SharedSelfTest();return{passed=shared and shared.passed==true,shared=shared,version=VERSION,exports={'GetV14Twin','StartTraumaEvolutionV14','CreateTraumaActivationV14','CreateProcedureChecklistV14','ActivateMassiveTransfusionV14','CompareTraumaDestinationsV14','CreateCriticalTransferPlanV14','GetV14OperationalDashboard'}}end)

AddEventHandler(DPN_MED.Events.StateChanged,function(target,patientCid,changedState,eventType,data)local s=type(changedState)=='table'and changedState or stateFor(target);if not s then return end;DPN_MED.CalculateV14Metrics(s);trend(target,s,eventType or'state_changed');event(target,eventType or'state_changed',data or{},'medical-core');if s.v14.traumaCommandRisk>=90 then pcall(function()exports['dpn-medical-core']:RaiseSafetyAlert(target,'v14_trauma_command_critical','critical','V14 trauma model predicts immediate preventable-death risk.',{risk=s.v14.traumaCommandRisk,goldenHour=s.v14.goldenHourRemaining,tier=s.v14.traumaTier,destination=s.v14.recommendedDestination},'dpn-medical-core-v14')end)end end)
CreateThread(function()Wait(5800);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-core-v14',VERSION,{'time_critical_trauma','occult_hemorrhage','compartment_syndrome','crush_rhabdomyolysis','balanced_resuscitation','transfusion_complications','airway_failure','neuroprotection','procedure_checklists','trauma_clocks','destination_optimization','critical_transfer_planning'})end);print('[dpn-medical-core] v14.0.0 time-critical trauma and resuscitation command active')end)
RegisterCommand('medv14',function(src,args)local target=tonumber(args[1]or src);local twin=exports['dpn-medical-core']:GetV14Twin(target);local msg=twin and('V14 risk %s%% | %s | golden hour %s min | occult bleed %s%% | airway %s%% | procedure %s%%'):format(twin.v14.traumaCommandRisk,twin.v14.traumaTier,twin.v14.goldenHourRemaining,twin.traumaV14.occultHemorrhageRisk,twin.airwayV14.airwayProtection,twin.procedureV14.readiness)or'Patient unavailable.';if src==0 then print(msg)else TriggerClientEvent('chat:addMessage',src,{args={'DPN Medical v14',msg}})end end,false)
RegisterCommand('medv14test',function(src)local r=exports['dpn-medical-core']:RunV14SelfTest();local s=r.shared or{};local msg=('V14 self-test passed=%s risk=%s occult=%s airway=%s procedure=%s steps=%s destination=%s'):format(tostring(r.passed),tostring(s.risk),tostring(s.occult),tostring(s.airway),tostring(s.procedure),tostring(s.steps),tostring(s.destination));if src==0 then print(msg)else TriggerClientEvent('chat:addMessage',src,{args={'DPN Medical v14',msg}})end end,false)
RegisterNetEvent('dpn-medical-core:server:requestV14Summary',function()local src=source;local twin=exports['dpn-medical-core']:GetV14Twin(src);TriggerClientEvent('dpn-medical-core:client:v14Summary',src,twin and('Risk %s%% | Tier %s | Golden hour %s min | Airway %s'):format(twin.v14.traumaCommandRisk,twin.v14.traumaTier,twin.v14.goldenHourRemaining,twin.airwayV14.airwayGrade)or'No medical state available.')end)
