local VERSION='11.0.0'
local simulations, scoring, competencies, remediation = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
exports('CreateAdaptiveSimulationV11',function(scenario,learners,difficulty,objectives)local item={id=uid('SIM11'),scenario=scenario,learners=learners or{},difficulty=tonumber(difficulty)or 1,objectives=objectives or{},events={},status='ready',createdAt=os.time()};simulations[item.id]=item;return item.id,item end)
exports('RecordSimulationActionV11',function(simId,learner,action,data)local sim=simulations[tostring(simId)];if not sim then return false,'Simulation not found.'end;sim.events[#sim.events+1]={learner=learner,action=action,data=data or{},at=os.time()};return true end)
exports('ScoreClinicalPerformanceV11',function(simId,rubric,evaluator)local sim=simulations[tostring(simId)];if not sim then return false,'Simulation not found.'end;local total,max=0,0;for _,item in ipairs(rubric or{})do total=total+(tonumber(item.score)or 0);max=max+(tonumber(item.max)or 0)end;local score=max>0 and math.floor(total/max*100)or 0;local result={id=uid('SCORE11'),simId=simId,evaluator=evaluator,score=score,status=score>=80 and'competent'or score>=65 and'developing'or'remediation_required',createdAt=os.time()};scoring[result.id]=result;return true,result end)
exports('AssignRemediationV11',function(provider,competency,plan,educator)local item={id=uid('REM11'),provider=provider,competency=competency,plan=plan or{},educator=educator,status='assigned',createdAt=os.time()};remediation[item.id]=item;return true,item end)
exports('RecordCompetencyV11',function(provider,competency,level,evaluator)local item={id=uid('COMP11'),provider=provider,competency=competency,level=level,evaluator=evaluator,createdAt=os.time()};competencies[item.id]=item;return true,item end)
exports('GetV11TrainingBoard',function()return{version=VERSION,simulations=simulations,scoring=scoring,competencies=competencies,remediation=remediation,generatedAt=os.time()}end)
CreateThread(function()Wait(7800);print('[dpn-medical-training] v11 adaptive simulation and competency management active')end)
