const app=document.getElementById('app'),callsEl=document.getElementById('calls'),unitsEl=document.getElementById('units'),statusEl=document.getElementById('status');
let calls={},units={},statuses={},callStatuses={},supervisor=false;
function post(name,data={}){return fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).catch(()=>{})}
function text(tag,value,className){const e=document.createElement(tag);if(className)e.className=className;e.textContent=String(value??'');return e}
function btn(label,cb,cls=''){const b=text('button',label,cls);b.onclick=cb;return b}
function timeline(call){const data=call.metadata&&call.metadata.timeline;if(!Array.isArray(data))return[];return data.slice(-6).reverse()}
function promptNote(call){const note=window.prompt(`Add note to ${call.callId}`);if(note)post('addNote',{callId:call.callId,note})}
function promptClose(call){const disposition=window.prompt(`Disposition for ${call.callId} (arrest, report, unfounded, transferred, etc.)`);if(!disposition)return;const notes=window.prompt('Closing notes')||'';post('closeCall',{callId:call.callId,disposition,notes})}
function promptPriority(call){const priority=window.prompt('New priority 1-5',String(call.priority||3));if(!priority)return;const reason=window.prompt('Reason for priority change')||'';post('setCallPriority',{callId:call.callId,priority,reason})}
function render(){
 statusEl.replaceChildren();Object.entries(statuses).forEach(([code,label])=>{const o=text('option',`${code} - ${label}`);o.value=code;statusEl.appendChild(o)});
 callsEl.replaceChildren();const list=Object.values(calls).sort((a,b)=>Number(a.priority||9)-Number(b.priority||9)||Number(b.createdAt||0)-Number(a.createdAt||0));if(!list.length)callsEl.appendChild(text('p','No active calls.'));
 list.forEach(call=>{const w=document.createElement('div');w.className=`call p${Math.max(1,Math.min(4,Number(call.priority)||3))}`;w.append(text('b',call.title||'Dispatch Call'),text('div',`${call.callId||'UNKNOWN'} | Priority ${call.priority||3} | ${callStatuses[call.status]||call.status||'active'} | ${call.type||'general'}`,'meta'));const d=text('p',call.description||'No description supplied.');d.style.whiteSpace='pre-wrap';w.appendChild(d);
  const assigned=Object.values(call.assigned||{}).map(x=>`${x.unit||x.name} (${x.status||'assigned'})`).join(', ');w.appendChild(text('div',`Assigned: ${assigned||'None'}`,'meta'));
  const tl=timeline(call);if(tl.length){const box=document.createElement('div');box.className='timeline';tl.forEach(x=>box.appendChild(text('div',`${x.actor||'System'}: ${x.text||x.type}`,'meta')));w.appendChild(box)}
  const a=document.createElement('div');a.className='actions';a.append(btn('Assign Self',()=>post('assignSelf',{callId:call.callId})),btn('En Route',()=>post('setCallStatus',{callId:call.callId,status:'enroute'})),btn('On Scene',()=>post('setCallStatus',{callId:call.callId,status:'on_scene'})),btn('Holding',()=>post('setCallStatus',{callId:call.callId,status:'holding'})),btn('Add Note',()=>promptNote(call)),btn('Waypoint',()=>post('waypoint',{callId:call.callId})));if(supervisor)a.append(btn('Priority',()=>promptPriority(call)),btn('Close',()=>promptClose(call),'danger'));w.appendChild(a);callsEl.appendChild(w)
 });
 unitsEl.replaceChildren();const ulist=Object.values(units);if(!ulist.length)unitsEl.appendChild(text('p','No units online.'));ulist.forEach(unit=>{const w=document.createElement('div');w.className='unit';w.append(text('b',unit.unit||unit.src||'UNIT'),text('div',unit.name||'Unknown'),text('div',`${unit.job||''} | ${unit.status||'10-8'}${unit.role?` | ${unit.role}`:''}`,'meta'));if(Array.isArray(unit.partners)&&unit.partners.length)w.appendChild(text('div',`Partners: ${unit.partners.join(', ')}`,'meta'));unitsEl.appendChild(w)})
}
window.addEventListener('message',event=>{const data=event.data||{};if(data.action==='open')app.classList.remove('hidden');if(data.action==='close')app.classList.add('hidden');if(data.action==='sync'){calls=data.calls||{};units=data.units||{};statuses=data.statuses||statuses;callStatuses=data.callStatuses||callStatuses;supervisor=data.supervisor===true;render()}});
document.getElementById('close').onclick=()=>post('close');document.addEventListener('keydown',event=>{if(event.key==='Escape')post('close')});document.getElementById('saveStatus').onclick=()=>post('setStatus',{status:statusEl.value});document.getElementById('saveUnit').onclick=()=>post('setUnit',{unit:document.getElementById('unit').value});document.getElementById('create').onclick=()=>post('createCall',{title:document.getElementById('title').value,type:document.getElementById('type').value,description:document.getElementById('desc').value});
