RegisterCommand('medicalv13', function()
    TriggerServerEvent('dpn-medical-core:server:requestV13Snapshot')
end, false)
RegisterNetEvent('dpn-medical-core:client:v13Summary', function(message)
    TriggerEvent('chat:addMessage', { color = { 98, 214, 255 }, args = { 'DPN Medical v13', tostring(message or 'No v13 data available.') } })
end)
CreateThread(function()
    Wait(4000)
    TriggerEvent('chat:addSuggestion', '/medicalv13', 'Show your DPN Medical v13 continuum summary')
end)
