local VERSION='10.0.0'
local organCommand, liberation, rounds = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateMultiOrganSupportCommandV10',function(target,team)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local supports={};if twin.bloodGas.oxygenationFailure or twin.bloodGas.ventilationFailure then supports[#supports+1]='mechanical_ventilation'end;if twin.v10.organCouplingFailure>=45 then supports[#supports+1]='hemodynamic_support'end;if twin.v9 and twin.v9.hepaticRisk>=40 then supports[#supports+1]='hepatic_support'end;if twin.v8 and twin.v8.renal and twin.v8.renal.akiStage>=2 then supports[#supports+1]='renal_support'end;local item={id=uid('MOS10'),target=tonumber(target),team=team or{},supports=supports,risk=twin.v10.commandRisk,status='active',createdAt=os.time()};organCommand[item.id]=item;return true,item end)
exports('EvaluateLiberationReadinessV10',function(target,parameters)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;parameters=type(parameters)=='table'and parameters or{};local ready=not twin.bloodGas.oxygenationFailure and not twin.bloodGas.ventilationFailure and twin.v10.commandRisk<45 and(tonumber(parameters.vasopressorDose)or 0)<=.1;local item={id=uid('LIB10'),target=tonumber(target),ready=ready,reasons=ready and{}or{'physiology_not_ready'},createdAt=os.time()};liberation[item.id]=item;return true,item end)
exports('CreateClosedLoopRoundsV10',function(target,team)local ok,twin=core('GetV10Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local item={id=uid('RND10'),target=tonumber(target),team=team or{},careGaps=twin.careGaps,goals={'airway','breathing','circulation','sedation','delirium','mobility','nutrition','devices','family'},createdAt=os.time()};rounds[item.id]=item;return true,item end)
exports('GetV10ICUBoard',function()return{version=VERSION,organCommand=organCommand,liberation=liberation,rounds=rounds,generatedAt=os.time()}end)
CreateThread(function()Wait(8300);print('[dpn-medical-icu] v10 multi-organ command and closed-loop rounds active')end)
