local VERSION='11.0.0'
local supportPlans, ventilators, liberation, dailyGoals = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateOrganSupportPlanV11',function(target,team)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local supports={};if twin.bloodGas.oxygenationFailure or twin.bloodGas.ventilationFailure then supports[#supports+1]='ventilation'end;if twin.microcirculation.tissueOxygenation<70 then supports[#supports+1]='hemodynamic_support'end;if twin.endocrine.endocrineRisk>=50 then supports[#supports+1]='metabolic_support'end;if twin.infection.probability>=65 then supports[#supports+1]='sepsis_bundle'end;local item={id=uid('ICU11'),target=tonumber(target),team=team or{},supports=supports,resourceIntensity=twin.v11.resourceIntensity,status='active',createdAt=os.time()};supportPlans[item.id]=item;return true,item end)
exports('CreateVentilatorStrategyV11',function(target,settings,actor)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;settings=type(settings)=='table'and settings or{};local weight=tonumber(twin.demographics.weightKg)or 80;local item={id=uid('VENT11'),target=tonumber(target),mode=settings.mode or'volume_control',tidalVolumeMl=settings.tidalVolumeMl or math.floor(weight*6),rate=settings.rate or 18,peep=settings.peep or(twin.bloodGas.oxygenationFailure and 10 or 5),fio2=settings.fio2 or(twin.bloodGas.oxygenationFailure and .8 or .4),actor=actor,status='active',createdAt=os.time()};ventilators[item.id]=item;return true,item end)
exports('PredictLiberationV11',function(target,parameters)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;parameters=type(parameters)=='table'and parameters or{};local score=100-twin.v11.autonomousRisk*.45-twin.recovery.frailty*.25-twin.recovery.deliriumRisk*.15-(tonumber(parameters.vasopressorDose)or 0)*100;local item={id=uid('LIB11'),target=tonumber(target),score=math.floor(math.max(0,math.min(100,score))),ready=score>=70 and not twin.bloodGas.oxygenationFailure and not twin.bloodGas.ventilationFailure,reasons={},createdAt=os.time()};if not item.ready then item.reasons={'physiology_or_support_requirements_not_ready'}end;liberation[item.id]=item;return true,item end)
exports('CreateDailyGoalsV11',function(target,team)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local item={id=uid('GOAL11'),target=tonumber(target),team=team or{},goals={'close_care_gaps','review_devices','sedation_and_delirium','nutrition','mobility','family_communication'},recommendations=twin.recommendations,status='active',createdAt=os.time()};dailyGoals[item.id]=item;return true,item end)
exports('GetV11ICUBoard',function()return{version=VERSION,supportPlans=supportPlans,ventilators=ventilators,liberation=liberation,dailyGoals=dailyGoals,generatedAt=os.time()}end)
CreateThread(function()Wait(8300);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-icu',VERSION,{'organ_support_plans','ventilator_strategy','liberation_prediction','daily_goals'})end);print('[dpn-medical-icu] v11 organ-support planning and ventilator strategy active')end)
