local VERSION='9.0.0'
local bundles, liberation, rounds = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateAdaptiveOrganSupportBundleV9',function(target)
 local ok,twin=core('GetV9Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local actions={};if twin.pulmonary and twin.pulmonary.pfRatio<200 then actions[#actions+1]='lung_protective_ventilation'end;if twin.renal and twin.renal.akiStage>=2 then actions[#actions+1]='renal_protection'end;if twin.hemodynamics and twin.hemodynamics.cardiacOutputLpm<3 then actions[#actions+1]='hemodynamic_optimization'end;if twin.v9.electrolyteRisk>=35 then actions[#actions+1]='electrolyte_correction'end
 local item={id=uid('ICUB'),target=tonumber(target),actions=actions,risk=twin.v9.adaptiveRisk,status='active',createdAt=os.time()};bundles[item.id]=item;return true,item
end)
exports('EvaluateVentilatorLiberationV9',function(target,parameters)local ok,twin=core('GetV9Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;parameters=type(parameters)=='table'and parameters or{};local ready=(twin.pulmonary.pfRatio or 0)>=200 and(twin.v9.adaptiveRisk or 100)<55 and(tonumber(parameters.peep)or 5)<=8 and(tonumber(parameters.fio2)or .4)<=.5;local item={id=uid('SBT'),target=tonumber(target),ready=ready,reasons={},createdAt=os.time()};if not ready then item.reasons={'oxygenation_or_risk_not_ready'}end;liberation[item.id]=item;return true,item end)
exports('CreateDailyICURoundsV9',function(target,team)local ok,twin=core('GetV9Twin',target);if not ok or type(twin)~='table'then return false,'Patient unavailable.'end;local item={id=uid('ROUND'),target=tonumber(target),team=team or{},goals={'review_devices','review_sedation','review_antibiotics','review_mobility','review_nutrition'},adaptiveRisk=twin.v9.adaptiveRisk,createdAt=os.time()};rounds[item.id]=item;return true,item end)
exports('GetV9ICUBoard',function()return{version=VERSION,bundles=bundles,liberation=liberation,rounds=rounds,generatedAt=os.time()}end)
CreateThread(function()Wait(6300);print('[dpn-medical-icu] v9 adaptive organ support and liberation planning active')end)
