local VERSION='9.0.0'
local trends, rosc, cpr = {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('AnalyzeWaveformTrendV9',function(target,samples) samples=type(samples)=='table'and samples or{};local hrSum,qtSum=0,0;for _,s in ipairs(samples)do hrSum=hrSum+(tonumber(s.hr)or 0);qtSum=qtSum+(tonumber(s.qtc)or 0)end;local n=math.max(1,#samples);local item={id=uid('WAVE'),target=tonumber(target),averageHr=math.floor(hrSum/n),averageQtc=math.floor(qtSum/n),risk=qtSum/n>=500 and'high'or'normal',samples=#samples,createdAt=os.time()};trends[item.id]=item;core('RecordDeviceTelemetry',target,'lifepak_waveform',item,'dpn-medical-lifepak');return true,item end)
exports('RecordROSCBundleV9',function(target,data,actor)local item={id=uid('ROSC'),target=tonumber(target),data=data or{},actor=actor,completed={oxygenation=true,bloodPressureTarget=true,temperatureControl=data and data.temperatureControl==true,ecg=data and data.ecg==true},createdAt=os.time()};rosc[item.id]=item;return true,item end)
exports('CalculateCPRQualityTrendV9',function(sessionId,segments)local depth,rate,recoil=0,0,0;segments=type(segments)=='table'and segments or{};for _,s in ipairs(segments)do depth=depth+(tonumber(s.depth)or 0);rate=rate+(tonumber(s.rate)or 0);recoil=recoil+(tonumber(s.recoil)or 0)end;local n=math.max(1,#segments);local score=math.max(0,100-math.abs(depth/n-5.5)*15-math.abs(rate/n-110)*.8-math.max(0,100-recoil/n)*.4);local item={id=uid('CPR9'),sessionId=sessionId,score=math.floor(score),segments=#segments,createdAt=os.time()};cpr[item.id]=item;return item end)
exports('GetV9LifepakBoard',function()return{version=VERSION,trends=trends,rosc=rosc,cpr=cpr,generatedAt=os.time()}end)
CreateThread(function()Wait(6500);print('[dpn-medical-lifepak] v9 waveform trends, ROSC and CPR quality active')end)
