-- DPN-MDT database schema
-- Import this after qb-core and oxmysql are installed.

CREATE TABLE IF NOT EXISTS `dpn_mdt_dispatch_calls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `call_id` VARCHAR(64) NOT NULL UNIQUE,
  `code` VARCHAR(32) DEFAULT '911',
  `title` VARCHAR(160) NOT NULL,
  `description` LONGTEXT,
  `priority` VARCHAR(32) DEFAULT 'normal',
  `status` VARCHAR(32) DEFAULT 'new',
  `department` VARCHAR(64) DEFAULT 'shared',
  `caller` VARCHAR(120) DEFAULT 'Unknown',
  `location` VARCHAR(180) DEFAULT 'Unknown Location',
  `coords` LONGTEXT,
  `assigned_units` LONGTEXT,
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_call_status` (`status`),
  INDEX `idx_call_department` (`department`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_unit_status` (
  `citizenid` VARCHAR(64) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `department` VARCHAR(64) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'available',
  `call_id` VARCHAR(64) DEFAULT '',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`citizenid`),
  INDEX `idx_unit_department` (`department`),
  INDEX `idx_unit_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(64) DEFAULT 'incident',
  `title` VARCHAR(180) NOT NULL,
  `narrative` LONGTEXT,
  `status` VARCHAR(32) DEFAULT 'open',
  `priority` VARCHAR(32) DEFAULT 'normal',
  `author_citizenid` VARCHAR(64),
  `author_name` VARCHAR(120),
  `department` VARCHAR(64),
  `involved` LONGTEXT,
  `evidence` LONGTEXT,
  `charges` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `ft_report_search` (`title`, `narrative`),
  INDEX `idx_report_status` (`status`),
  INDEX `idx_report_department` (`department`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_cases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `case_no` VARCHAR(64) NOT NULL UNIQUE,
  `title` VARCHAR(180) NOT NULL,
  `summary` LONGTEXT,
  `status` VARCHAR(32) DEFAULT 'open',
  `priority` VARCHAR(32) DEFAULT 'normal',
  `lead_citizenid` VARCHAR(64),
  `lead_name` VARCHAR(120),
  `department` VARCHAR(64),
  `linked_reports` LONGTEXT,
  `involved` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_case_status` (`status`),
  INDEX `idx_case_no` (`case_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_bolos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bolo_type` VARCHAR(32) DEFAULT 'person',
  `title` VARCHAR(180) NOT NULL,
  `description` LONGTEXT,
  `plate` VARCHAR(32) DEFAULT '',
  `citizenid` VARCHAR(64) DEFAULT '',
  `priority` VARCHAR(32) DEFAULT 'normal',
  `status` VARCHAR(32) DEFAULT 'active',
  `created_by` VARCHAR(120),
  `department` VARCHAR(64),
  `expires_at` DATETIME NULL,
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_bolo_status` (`status`),
  INDEX `idx_bolo_plate` (`plate`),
  INDEX `idx_bolo_cid` (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_warrants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `citizenid` VARCHAR(64) NOT NULL,
  `suspect_name` VARCHAR(120) DEFAULT '',
  `title` VARCHAR(180) NOT NULL,
  `reason` LONGTEXT,
  `charges` LONGTEXT,
  `status` VARCHAR(32) DEFAULT 'active',
  `signed_by` VARCHAR(120),
  `department` VARCHAR(64),
  `expires_at` DATETIME NULL,
  `served_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_warrant_cid` (`citizenid`),
  INDEX `idx_warrant_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_evidence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evidence_no` VARCHAR(64) NOT NULL UNIQUE,
  `evidence_type` VARCHAR(64) DEFAULT 'general',
  `title` VARCHAR(180) NOT NULL,
  `description` LONGTEXT,
  `serial` VARCHAR(120) DEFAULT '',
  `location` VARCHAR(180) DEFAULT '',
  `status` VARCHAR(32) DEFAULT 'stored',
  `chain_of_custody` LONGTEXT,
  `linked_case` VARCHAR(64),
  `linked_report` INT NULL,
  `created_by` VARCHAR(120),
  `department` VARCHAR(64),
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_evidence_no` (`evidence_no`),
  INDEX `idx_evidence_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_weapons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `citizenid` VARCHAR(64) NOT NULL,
  `weapon_name` VARCHAR(120) NOT NULL,
  `serial` VARCHAR(120) NOT NULL,
  `info` LONGTEXT,
  `status` VARCHAR(32) DEFAULT 'registered',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_weapon_serial` (`serial`),
  INDEX `idx_weapon_cid` (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_charges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL UNIQUE,
  `title` VARCHAR(180) NOT NULL,
  `category` VARCHAR(80) DEFAULT 'general',
  `class` VARCHAR(64) DEFAULT 'misdemeanor',
  `fine` INT DEFAULT 0,
  `jail` INT DEFAULT 0,
  `points` INT DEFAULT 0,
  `description` LONGTEXT,
  `active` TINYINT(1) DEFAULT 1,
  `sort_order` INT DEFAULT 0,
  `created_by` VARCHAR(120) DEFAULT 'system',
  `updated_by` VARCHAR(120) DEFAULT 'system',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_charge_category` (`category`),
  INDEX `idx_charge_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS `dpn_mdt_citizen_charges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `charge_no` VARCHAR(64) NOT NULL UNIQUE,
  `citizenid` VARCHAR(64) NOT NULL,
  `citizen_name` VARCHAR(120) DEFAULT '',
  `charge_type` VARCHAR(64) DEFAULT 'arrest',
  `status` VARCHAR(64) DEFAULT 'filed',
  `linked_report_id` INT NULL,
  `linked_case_no` VARCHAR(64) DEFAULT '',
  `linked_warrant_id` INT NULL,
  `linked_court_docket` VARCHAR(64) DEFAULT '',
  `charges` LONGTEXT NOT NULL,
  `total_fine` INT DEFAULT 0,
  `total_jail` INT DEFAULT 0,
  `total_points` INT DEFAULT 0,
  `notes` LONGTEXT,
  `arresting_officer_citizenid` VARCHAR(64) DEFAULT '',
  `arresting_officer_name` VARCHAR(120) DEFAULT '',
  `department` VARCHAR(64) DEFAULT 'shared',
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_citizen_charges_cid` (`citizenid`),
  INDEX `idx_citizen_charges_no` (`charge_no`),
  INDEX `idx_citizen_charges_status` (`status`),
  INDEX `idx_citizen_charges_report` (`linked_report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_court_cases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `docket_no` VARCHAR(64) NOT NULL UNIQUE,
  `title` VARCHAR(180) NOT NULL,
  `case_type` VARCHAR(64) DEFAULT 'criminal',
  `plaintiff` LONGTEXT,
  `defendant` LONGTEXT,
  `charges` LONGTEXT,
  `status` VARCHAR(64) DEFAULT 'filed',
  `judge` VARCHAR(120) DEFAULT '',
  `next_hearing` DATETIME NULL,
  `notes` LONGTEXT,
  `created_by` VARCHAR(120),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_court_status` (`status`),
  INDEX `idx_docket_no` (`docket_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_medical_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `incident_id` VARCHAR(64) NOT NULL UNIQUE,
  `patient_citizenid` VARCHAR(64) DEFAULT '',
  `patient_name` VARCHAR(120) DEFAULT '',
  `triage` VARCHAR(32) DEFAULT 'green',
  `complaint` LONGTEXT,
  `assessment` LONGTEXT,
  `treatment` LONGTEXT,
  `transport_to` VARCHAR(180) DEFAULT '',
  `status` VARCHAR(32) DEFAULT 'open',
  `provider_name` VARCHAR(120),
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_med_patient` (`patient_citizenid`),
  INDEX `idx_med_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_fire_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `incident_id` VARCHAR(64) NOT NULL UNIQUE,
  `incident_type` VARCHAR(80) DEFAULT 'structure_fire',
  `address` VARCHAR(180) DEFAULT '',
  `cause` VARCHAR(120) DEFAULT 'undetermined',
  `conditions` LONGTEXT,
  `actions_taken` LONGTEXT,
  `units` LONGTEXT,
  `hazards` LONGTEXT,
  `status` VARCHAR(32) DEFAULT 'open',
  `officer_name` VARCHAR(120),
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_fire_status` (`status`),
  INDEX `idx_fire_type` (`incident_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_fire_preplans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `building_name` VARCHAR(180) NOT NULL,
  `address` VARCHAR(180) DEFAULT '',
  `occupancy` VARCHAR(120) DEFAULT '',
  `hazards` LONGTEXT,
  `hydrants` LONGTEXT,
  `utilities` LONGTEXT,
  `access_points` LONGTEXT,
  `contact_info` LONGTEXT,
  `notes` LONGTEXT,
  `created_by` VARCHAR(120),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_preplan_address` (`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `dpn_mdt_corrections_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `record_no` VARCHAR(64) NOT NULL UNIQUE,
  `citizenid` VARCHAR(64) DEFAULT '',
  `inmate_name` VARCHAR(120) DEFAULT '',
  `custody_status` VARCHAR(64) DEFAULT 'active',
  `housing` VARCHAR(120) DEFAULT '',
  `movement_log` LONGTEXT,
  `disciplinary` LONGTEXT,
  `medical_flags` LONGTEXT,
  `notes` LONGTEXT,
  `created_by` VARCHAR(120),
  `department` VARCHAR(64) DEFAULT 'corrections',
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_corr_cid` (`citizenid`),
  INDEX `idx_corr_status` (`custody_status`),
  INDEX `idx_corr_record` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS `dpn_mdt_citizen_notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `citizenid` VARCHAR(64) NOT NULL,
  `note_type` VARCHAR(64) DEFAULT 'general',
  `body` LONGTEXT,
  `created_by` VARCHAR(120),
  `department` VARCHAR(64) DEFAULT 'shared',
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_citizen_notes_cid` (`citizenid`),
  INDEX `idx_citizen_notes_type` (`note_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_vehicle_flags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(32) NOT NULL,
  `flag_type` VARCHAR(64) DEFAULT 'watch',
  `title` VARCHAR(180) NOT NULL,
  `notes` LONGTEXT,
  `status` VARCHAR(32) DEFAULT 'active',
  `created_by` VARCHAR(120),
  `department` VARCHAR(64) DEFAULT 'shared',
  `metadata` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_vehicle_flags_plate` (`plate`),
  INDEX `idx_vehicle_flags_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_bulletins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `body` LONGTEXT,
  `department` VARCHAR(64) DEFAULT 'shared',
  `priority` VARCHAR(32) DEFAULT 'normal',
  `created_by` VARCHAR(120),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_bulletin_dept` (`department`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dpn_mdt_audit_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actor_citizenid` VARCHAR(64) DEFAULT '',
  `actor_name` VARCHAR(120) DEFAULT '',
  `department` VARCHAR(64) DEFAULT 'system',
  `category` VARCHAR(64) NOT NULL,
  `action` VARCHAR(120) NOT NULL,
  `target` VARCHAR(180) DEFAULT '',
  `details` LONGTEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_audit_actor` (`actor_citizenid`),
  INDEX `idx_audit_category` (`category`),
  INDEX `idx_audit_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `dpn_mdt_charges` (`code`, `title`, `category`, `class`, `fine`, `jail`, `points`, `description`, `sort_order`) VALUES
('PO-101', 'Failure to Obey Lawful Order', 'public_order', 'misdemeanor', 750, 5, 0, 'Refusing a lawful order from authorized public-safety or court personnel.', 1),
('PO-102', 'Obstruction of Government Operations', 'public_order', 'misdemeanor', 1250, 10, 0, 'Interfering with a lawful investigation, emergency response, court, or custody operation.', 2),
('PO-103', 'Disorderly Conduct', 'public_order', 'infraction', 500, 0, 0, 'Creating a public disturbance or unreasonable public-safety disruption.', 3),
('PO-104', 'False Report to Emergency Services', 'public_order', 'misdemeanor', 1500, 10, 0, 'Knowingly making a false or misleading emergency report.', 4),
('PO-105', 'Resisting Arrest', 'public_order', 'misdemeanor', 2500, 15, 0, 'Physically or intentionally resisting detention, arrest, or lawful transport.', 5),
('PO-106', 'Interference at Emergency Scene', 'public_order', 'misdemeanor', 1500, 10, 0, 'Entering or disrupting a secured emergency scene after warning.', 6),
('PO-107', 'Impersonating Public-Safety Personnel', 'public_order', 'felony', 7500, 35, 0, 'Pretending to be law enforcement, EMS, fire, court, corrections, or authorized staff.', 7),
('PO-108', 'Tampering with Government Equipment', 'public_order', 'felony', 6500, 30, 0, 'Damaging, disabling, hiding, or misusing government or emergency equipment.', 8),
('PO-109', 'Failure to Identify During Lawful Detention', 'public_order', 'infraction', 650, 0, 0, 'Refusing to provide required identity during a lawful detention.', 9),
('PO-110', 'Harassment of Public-Safety Personnel', 'public_order', 'misdemeanor', 2000, 10, 0, 'Threatening, stalking, or harassing public-safety personnel during or because of duties.', 10),
('PO-111', 'Aiding and Abetting', 'public_order', 'misdemeanor', 3000, 15, 0, 'Assisting, encouraging, or facilitating another offense.', 11),
('PO-112', 'Criminal Threats', 'public_order', 'misdemeanor', 3500, 15, 0, 'Threatening violence or serious harm in a credible manner.', 12),
('TR-201', 'Speeding 1-15 Over', 'traffic', 'infraction', 300, 0, 1, 'Operating a vehicle 1 to 15 mph over the posted speed limit.', 13),
('TR-202', 'Speeding 16-30 Over', 'traffic', 'infraction', 750, 0, 2, 'Operating a vehicle 16 to 30 mph over the posted speed limit.', 14),
('TR-203', 'Excessive Speeding 31+', 'traffic', 'misdemeanor', 1500, 5, 3, 'Operating a vehicle 31 or more mph over the posted speed limit.', 15),
('TR-204', 'Reckless Driving', 'traffic', 'misdemeanor', 2500, 10, 3, 'Driving with willful disregard for life, property, or roadway safety.', 16),
('TR-205', 'Failure to Yield to Emergency Vehicle', 'traffic', 'infraction', 1000, 0, 2, 'Failing to yield to active emergency lights or sirens.', 17),
('TR-206', 'Street Racing', 'traffic', 'misdemeanor', 3500, 15, 4, 'Participating in an unlawful speed contest or organized street race.', 18),
('TR-207', 'Hit and Run', 'traffic', 'felony', 6500, 25, 6, 'Leaving the scene of a collision without reporting or rendering required aid.', 19),
('TR-208', 'Evading Emergency Personnel', 'traffic', 'felony', 7500, 25, 6, 'Fleeing or attempting to elude emergency personnel.', 20),
('TR-209', 'Felony Eluding with Injury Risk', 'traffic', 'felony', 12000, 45, 8, 'Eluding in a manner creating substantial risk of serious injury.', 21),
('TR-210', 'Driving Without a Valid License', 'traffic', 'infraction', 800, 0, 2, 'Operating a motor vehicle without a valid driver license.', 22),
('TR-211', 'Driving with Suspended License', 'traffic', 'misdemeanor', 1800, 5, 4, 'Operating a motor vehicle while driving privileges are suspended.', 23),
('TR-212', 'Operating an Unregistered Vehicle', 'traffic', 'infraction', 600, 0, 1, 'Operating a vehicle without valid registration.', 24),
('TR-213', 'Improper Passing / Unsafe Lane Change', 'traffic', 'infraction', 500, 0, 1, 'Unsafe lane movement, improper passing, or unsafe merge.', 25),
('TR-214', 'Failure to Stop at Signal / Stop Sign', 'traffic', 'infraction', 650, 0, 2, 'Failing to obey a traffic-control signal or stop sign.', 26),
('TR-215', 'DUI / Impaired Driving', 'traffic', 'misdemeanor', 5000, 20, 6, 'Operating a vehicle while impaired by alcohol, drugs, or other substances.', 27),
('TR-216', 'DUI Causing Injury', 'traffic', 'felony', 12500, 55, 8, 'Impaired driving that causes or risks serious bodily injury.', 28),
('TR-217', 'Vehicular Manslaughter', 'traffic', 'felony', 25000, 120, 10, 'Unlawfully causing death through dangerous or impaired vehicle operation.', 29),
('TR-218', 'Careless Operation of Emergency Vehicle', 'traffic', 'misdemeanor', 2500, 10, 0, 'Unsafe use of an emergency vehicle outside approved SOP or lawful necessity.', 30),
('TR-219', 'Illegal Parking / Blocking Emergency Access', 'traffic', 'infraction', 750, 0, 1, 'Parking in a way that blocks hydrants, lanes, hospital access, or emergency routes.', 31),
('TR-220', 'Commercial Vehicle Violation', 'traffic', 'infraction', 1200, 0, 2, 'Operating a commercial vehicle in violation of route, weight, cargo, or safety rules.', 32),
('TR-221', 'Operating Unsafe Vehicle', 'traffic', 'infraction', 1000, 0, 2, 'Driving a vehicle with unsafe equipment or damage.', 33),
('TR-222', 'No Proof of Insurance', 'traffic', 'infraction', 900, 0, 1, 'Failing to provide proof of valid vehicle insurance.', 34),
('TR-223', 'Fleeing Checkpoint / Roadblock', 'traffic', 'felony', 9000, 35, 6, 'Bypassing or fleeing a lawful checkpoint or emergency roadblock.', 35),
('VC-301', 'Simple Assault', 'violent', 'misdemeanor', 2500, 15, 0, 'Unlawful attempted or actual physical attack causing minor or no injury.', 36),
('VC-302', 'Aggravated Assault', 'violent', 'felony', 8500, 35, 0, 'Assault involving serious injury, a weapon, or elevated risk.', 37),
('VC-303', 'Assault on Emergency Personnel', 'violent', 'felony', 10000, 40, 0, 'Assault against law enforcement, EMS, fire, courts, corrections, or authorized emergency staff.', 38),
('VC-304', 'Battery', 'violent', 'misdemeanor', 4000, 20, 0, 'Intentional unlawful physical contact causing harm.', 39),
('VC-305', 'Aggravated Battery', 'violent', 'felony', 9500, 45, 0, 'Battery causing serious injury or involving a weapon.', 40),
('VC-306', 'Kidnapping', 'violent', 'felony', 18000, 75, 0, 'Unlawfully seizing, confining, or transporting another person.', 41),
('VC-307', 'Hostage Taking', 'violent', 'felony', 22000, 90, 0, 'Holding a person to compel action, ransom, or negotiation.', 42),
('VC-308', 'Attempted Murder', 'violent', 'felony', 25000, 90, 0, 'Attempting to unlawfully kill another person.', 43),
('VC-309', 'Murder', 'violent', 'capital', 50000, 999, 0, 'Unlawful killing of another person.', 44),
('VC-310', 'Manslaughter', 'violent', 'felony', 30000, 150, 0, 'Unlawfully causing death without premeditation.', 45),
('VC-311', 'Terroristic Threat / Mass Violence Threat', 'violent', 'felony', 30000, 150, 0, 'Threatening mass violence or causing major public fear/disruption.', 46),
('VC-312', 'Torture / Cruel Treatment', 'violent', 'felony', 35000, 180, 0, 'Intentional infliction of extreme pain or cruel treatment.', 47),
('VC-313', 'Reckless Endangerment', 'violent', 'misdemeanor', 3000, 15, 0, 'Creating a substantial risk of injury through reckless conduct.', 48),
('VC-314', 'Unlawful Detainment', 'violent', 'misdemeanor', 5000, 20, 0, 'Restricting another person without lawful authority.', 49),
('PT-401', 'Petty Theft', 'property', 'misdemeanor', 1500, 10, 0, 'Theft of low-value property.', 50),
('PT-402', 'Grand Theft', 'property', 'felony', 6500, 30, 0, 'Theft of high-value property.', 51),
('PT-403', 'Burglary', 'property', 'felony', 8000, 35, 0, 'Unlawful entry with intent to commit an offense.', 52),
('PT-404', 'Robbery', 'property', 'felony', 12000, 45, 0, 'Taking property by force, threat, or intimidation.', 53),
('PT-405', 'Armed Robbery', 'property', 'felony', 18000, 60, 0, 'Robbery involving a firearm, weapon, or dangerous instrument.', 54),
('PT-406', 'Vandalism', 'property', 'misdemeanor', 1500, 5, 0, 'Damaging or defacing property.', 55),
('PT-407', 'Arson', 'property', 'felony', 20000, 70, 0, 'Intentionally setting fire to property, vehicles, or structures.', 56),
('PT-408', 'Vehicle Theft', 'property', 'felony', 7500, 30, 0, 'Stealing or unlawfully taking a motor vehicle.', 57),
('PT-409', 'Possession of Stolen Property', 'property', 'misdemeanor', 3500, 15, 0, 'Possessing property known or reasonably believed to be stolen.', 58),
('PT-410', 'Trespassing', 'property', 'infraction', 600, 0, 0, 'Entering or remaining on property after notice or without permission.', 59),
('PT-411', 'Criminal Mischief', 'property', 'misdemeanor', 1800, 5, 0, 'Recklessly damaging or interfering with property use.', 60),
('PT-412', 'Tampering with Evidence', 'property', 'felony', 9000, 35, 0, 'Destroying, hiding, altering, or fabricating evidence.', 61),
('PT-413', 'Possession of Burglary Tools', 'property', 'misdemeanor', 2200, 10, 0, 'Possession of tools intended for unlawful entry or theft.', 62),
('PT-414', 'Looting During Emergency', 'property', 'felony', 10000, 45, 0, 'Theft or burglary during a declared emergency, disaster, or evacuation.', 63),
('ND-501', 'Possession of Controlled Substance', 'narcotics', 'misdemeanor', 2500, 10, 0, 'Possession of illegal narcotics or controlled substances.', 64),
('ND-502', 'Possession with Intent to Distribute', 'narcotics', 'felony', 9000, 35, 0, 'Possession with indicators of sale, packaging, or distribution.', 65),
('ND-503', 'Drug Manufacturing', 'narcotics', 'felony', 12500, 45, 0, 'Manufacturing or processing controlled substances.', 66),
('ND-504', 'Drug Trafficking', 'narcotics', 'felony', 20000, 75, 0, 'Large-scale transport, sale, or trafficking of controlled substances.', 67),
('ND-505', 'Possession of Drug Paraphernalia', 'narcotics', 'infraction', 750, 0, 0, 'Possession of equipment or items used for illegal drug activity.', 68),
('ND-506', 'Distribution Near Protected Location', 'narcotics', 'felony', 12000, 45, 0, 'Distribution near a school, hospital, courthouse, emergency facility, or correctional facility.', 69),
('ND-507', 'Prescription Fraud', 'narcotics', 'felony', 9000, 35, 0, 'Obtaining or attempting to obtain controlled medication by fraud.', 70),
('ND-508', 'Operating Drug Lab', 'narcotics', 'felony', 18000, 70, 0, 'Maintaining a location or vehicle for drug manufacture or processing.', 71),
('ND-509', 'Public Intoxication', 'narcotics', 'infraction', 500, 0, 0, 'Being intoxicated in public and creating a disturbance or safety risk.', 72),
('ND-510', 'Possession of Large Quantity Narcotics', 'narcotics', 'felony', 15000, 60, 0, 'Possession of a large quantity of narcotics exceeding personal-use amounts.', 73),
('WP-601', 'Unlawful Possession of Firearm', 'weapons', 'felony', 7500, 30, 0, 'Possessing a firearm without lawful authorization.', 74),
('WP-602', 'Brandishing a Weapon', 'weapons', 'misdemeanor', 3500, 15, 0, 'Displaying a weapon in a threatening or unsafe manner.', 75),
('WP-603', 'Discharge of Firearm in Public', 'weapons', 'felony', 8000, 35, 0, 'Firing a weapon in a public area without lawful justification.', 76),
('WP-604', 'Possession of Illegal Weapon', 'weapons', 'felony', 10000, 40, 0, 'Possession of prohibited weapons or illegal weapon modifications.', 77),
('WP-605', 'Felon in Possession of Firearm', 'weapons', 'felony', 15000, 60, 0, 'Possession of a firearm by a prohibited person.', 78),
('WP-606', 'Possession of Stolen Firearm', 'weapons', 'felony', 12000, 45, 0, 'Possession of a firearm known or reasonably believed to be stolen.', 79),
('WP-607', 'Illegal Sale of Firearm', 'weapons', 'felony', 15000, 55, 0, 'Unlawful sale, transfer, or trafficking of firearms.', 80),
('WP-608', 'Criminal Use of Explosive Device', 'weapons', 'felony', 30000, 150, 0, 'Use or attempted use of explosive device for criminal purposes.', 81),
('WP-609', 'Possession of Explosive Device', 'weapons', 'felony', 25000, 100, 0, 'Possessing an explosive device without lawful authorization.', 82),
('WP-610', 'Failure to Secure Firearm', 'weapons', 'misdemeanor', 2500, 10, 0, 'Negligent storage or handling resulting in public risk.', 83),
('WP-611', 'Weapon at Secure Facility', 'weapons', 'felony', 9000, 35, 0, 'Possessing a weapon inside a courthouse, jail, hospital, emergency command post, or secure facility.', 84),
('FC-701', 'Fraud', 'financial', 'felony', 7000, 30, 0, 'Using deception for unlawful financial gain.', 85),
('FC-702', 'Identity Theft', 'financial', 'felony', 10000, 40, 0, 'Using another identity or records without authorization.', 86),
('FC-703', 'Money Laundering', 'financial', 'felony', 17500, 70, 0, 'Concealing or transferring funds connected to criminal proceeds.', 87),
('FC-704', 'Forgery', 'financial', 'felony', 7500, 30, 0, 'Creating, altering, or using false documents, checks, IDs, or records.', 88),
('FC-705', 'Embezzlement', 'financial', 'felony', 12000, 45, 0, 'Fraudulent conversion of entrusted funds or property.', 89),
('FC-706', 'Bribery', 'financial', 'felony', 14000, 50, 0, 'Offering or accepting value to influence official action.', 90),
('FC-707', 'Extortion', 'financial', 'felony', 13000, 45, 0, 'Obtaining money, property, or action through threats or coercion.', 91),
('FC-708', 'Tax / Business License Violation', 'financial', 'civil', 2500, 0, 0, 'Operating without required licensing, permits, or tax compliance in RP systems.', 92),
('CT-801', 'Contempt of Court', 'courts', 'misdemeanor', 2500, 10, 0, 'Disobeying a lawful court order or disrupting court proceedings.', 93),
('CT-802', 'Failure to Appear', 'courts', 'misdemeanor', 3000, 15, 0, 'Failing to appear for a scheduled court hearing.', 94),
('CT-803', 'Perjury', 'courts', 'felony', 10000, 45, 0, 'Knowingly providing false sworn testimony or statements.', 95),
('CT-804', 'Witness Tampering', 'courts', 'felony', 12000, 50, 0, 'Attempting to influence, intimidate, or prevent witness testimony.', 96),
('CT-805', 'Jury Tampering', 'courts', 'felony', 12000, 50, 0, 'Attempting to influence or corrupt a jury member.', 97),
('CT-806', 'Violation of Protective Order', 'courts', 'misdemeanor', 3500, 15, 0, 'Violating a valid court protective or restraining order.', 98),
('CT-807', 'Obstruction of Justice', 'courts', 'felony', 11000, 45, 0, 'Interfering with the administration of justice.', 99),
('CT-808', 'Bail Bond Violation', 'courts', 'misdemeanor', 3500, 15, 0, 'Violating release, bond, or bail conditions.', 100),
('CR-901', 'Violation of Probation or Parole', 'corrections', 'misdemeanor', 2500, 20, 0, 'Violation of court or corrections release terms.', 101),
('CR-902', 'Escape from Custody', 'corrections', 'felony', 12000, 60, 0, 'Escaping, attempting to escape, or aiding escape from custody.', 102),
('CR-903', 'Contraband in Correctional Facility', 'corrections', 'felony', 9000, 40, 0, 'Possessing or introducing prohibited items into a detention facility.', 103),
('CR-904', 'Assault in Correctional Facility', 'corrections', 'felony', 10000, 45, 0, 'Assault committed inside or during correctional custody.', 104),
('CR-905', 'Inciting Riot in Correctional Facility', 'corrections', 'felony', 15000, 60, 0, 'Inciting or organizing disorder, riot, or coordinated disturbance in custody.', 105),
('CR-906', 'Failure to Comply with Custody Order', 'corrections', 'misdemeanor', 2000, 10, 0, 'Refusing lawful instructions during detention, transport, or booking.', 106),
('CR-907', 'Tampering with Monitoring Device', 'corrections', 'felony', 8000, 30, 0, 'Removing, damaging, or bypassing court/corrections monitoring equipment.', 107),
('CR-908', 'Unlawful Communication with Inmate', 'corrections', 'misdemeanor', 2500, 10, 0, 'Unauthorized messages, items, or contact with an inmate.', 108),
('ES-1001', 'Misuse of 911 / Emergency Network', 'emergency_services', 'infraction', 1000, 0, 0, 'Using emergency systems for non-emergency abuse or disruption.', 109),
('ES-1002', 'Interfering with Medical Treatment', 'emergency_services', 'misdemeanor', 2500, 10, 0, 'Blocking EMS treatment, triage, transport, or hospital care.', 110),
('ES-1003', 'Interfering with Fire Operations', 'emergency_services', 'misdemeanor', 2500, 10, 0, 'Blocking fire suppression, rescue, investigation, hydrant access, or evacuation.', 111),
('ES-1004', 'Failure to Evacuate Emergency Zone', 'emergency_services', 'infraction', 1000, 0, 0, 'Ignoring a lawful evacuation or exclusion order.', 112),
('ES-1005', 'False Fire Alarm / False Medical Call', 'emergency_services', 'misdemeanor', 1800, 10, 0, 'Knowingly causing false fire, rescue, or medical response.', 113),
('FR-1101', 'Hydrant Tampering', 'fire_rescue', 'misdemeanor', 2000, 10, 0, 'Tampering with hydrants, standpipes, fire alarms, or suppression equipment.', 114),
('FR-1102', 'Reckless Burning', 'fire_rescue', 'misdemeanor', 3500, 15, 0, 'Unsafe burning or negligent ignition creating fire risk.', 115),
('FR-1103', 'Arson Causing Injury Risk', 'fire_rescue', 'felony', 28000, 120, 0, 'Intentionally setting a fire that creates serious injury or mass casualty risk.', 116),
('MD-1201', 'Assault on Medical Staff', 'medical', 'felony', 10000, 45, 0, 'Assaulting EMS, hospital staff, or rescue personnel during medical operations.', 117),
('MD-1202', 'Hospital Security Violation', 'medical', 'misdemeanor', 2000, 10, 0, 'Trespass, disruption, weapon possession, or refusal to leave a hospital secure zone.', 118),
('AD-1301', 'Abuse of Government Database', 'admin', 'departmental', 5000, 20, 0, 'Unauthorized MDT/database lookup, disclosure, or misuse.', 119),
('AD-1302', 'Evidence Chain Violation', 'admin', 'departmental', 3500, 15, 0, 'Unauthorized evidence handling, broken chain of custody, or missing documentation.', 120),
('AD-1303', 'Emergency Override Abuse', 'admin', 'departmental', 7500, 30, 0, 'Misuse of admin/MIB emergency override or protected systems.', 121);


-- Existing-install upgrade helpers. If your SQL engine does not support IF NOT EXISTS on ALTER TABLE,
-- skip duplicate-column warnings or add these columns manually in your database panel.
ALTER TABLE `dpn_mdt_charges` ADD COLUMN IF NOT EXISTS `active` TINYINT(1) DEFAULT 1;
ALTER TABLE `dpn_mdt_charges` ADD COLUMN IF NOT EXISTS `sort_order` INT DEFAULT 0;
ALTER TABLE `dpn_mdt_charges` ADD COLUMN IF NOT EXISTS `created_by` VARCHAR(120) DEFAULT 'system';
ALTER TABLE `dpn_mdt_charges` ADD COLUMN IF NOT EXISTS `updated_by` VARCHAR(120) DEFAULT 'system';
