local VERSION='11.0.0'
local episodeCosts, scrubbedClaims, counseling, qualityAdjustments = {}, {}, {}, {}
local function uid(p)return('%s-%s-%04d'):format(p,os.time(),math.random(0,9999))end
local function core(name,...)local a=table.pack(...);local ok,x,y=pcall(function()local p=exports['dpn-medical-core'];return p[name](p,table.unpack(a,1,a.n))end);return ok,x,y end
exports('CreateEpisodeCostModelV11',function(target,charges,days)local ok,twin=core('GetV11Twin',target);if not ok then return false,'Patient unavailable.'end;local total=0;for _,c in ipairs(charges or{})do total=total+(tonumber(c.amount)or 0)end;local intensityMultiplier=1+twin.v11.resourceIntensity/200;local item={id=uid('COST11'),target=tonumber(target),charges=charges or{},days=tonumber(days)or 1,baseTotal=total,projectedTotal=math.floor(total*intensityMultiplier),resourceIntensity=twin.v11.resourceIntensity,createdAt=os.time()};episodeCosts[item.id]=item;return true,item end)
exports('ScrubClaimV11',function(claim,coding,documentation)local findings={};if not claim or not claim.patientCid then findings[#findings+1]='missing_patient'end;if not coding or#coding==0 then findings[#findings+1]='missing_codes'end;if not documentation or#documentation==0 then findings[#findings+1]='missing_documentation'end;local item={id=uid('SCRUB11'),claim=claim or{},findings=findings,status=#findings==0 and'clean'or'hold',createdAt=os.time()};scrubbedClaims[item.id]=item;return true,item end)
exports('CreateFinancialCounselingPlanV11',function(patientCid,balance,income,options,actor)local monthly=math.max(10,math.floor((tonumber(income)or 0)*.04));local months=math.ceil((tonumber(balance)or 0)/monthly);local item={id=uid('FIN11'),patientCid=patientCid,balance=balance,income=income,options=options or{},recommendedMonthly=monthly,recommendedMonths=months,actor=actor,status='offered',createdAt=os.time()};counseling[item.id]=item;return true,item end)
exports('ApplyQualityAdjustmentV11',function(episodeId,metrics,actor)local score=tonumber(metrics and metrics.qualityScore)or 100;local adjustment=score>=90 and-0.05 or score<60 and .1 or 0;local item={id=uid('QADJ11'),episodeId=episodeId,metrics=metrics or{},adjustment=adjustment,actor=actor,createdAt=os.time()};qualityAdjustments[item.id]=item;return true,item end)
exports('GetV11BillingBoard',function()return{version=VERSION,episodeCosts=episodeCosts,scrubbedClaims=scrubbedClaims,counseling=counseling,qualityAdjustments=qualityAdjustments,generatedAt=os.time()}end)
CreateThread(function()Wait(8700);pcall(function()exports['dpn-medical-core']:RegisterModule('dpn-medical-billing-plus',VERSION,{'episode_cost_model','claim_scrubbing','financial_counseling','quality_adjustment'})end);print('[dpn-medical-billing-plus] v11 episode costing and financial counseling active')end)
