#!/usr/bin/env python3
"""Generate the official DPN FiveM script index."""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
FRAMEWORKS = ("qbcore", "standalone", "hybrid")
FRAMEWORK_LABELS = {
    "qbcore": "QBCore",
    "standalone": "Standalone",
    "hybrid": "Hybrid",
}
DISPLAY_REPLACEMENTS = (
    ("Dpn ", "DPN "),
    ("Dpn-", "DPN-"),
    ("Icu", "ICU"),
    ("Pg 7x", "PG-7X"),
)

def format_display_name(value: object) -> str:
    name = str(value or "Unnamed")
    for source, replacement in DISPLAY_REPLACEMENTS:
        name = name.replace(source, replacement)
    return name

records = []
for framework in FRAMEWORKS:
    for metadata in (ROOT / framework).rglob("resource.json"):
        if "templates" in metadata.parts:
            continue
        try:
            data = json.loads(metadata.read_text(encoding="utf-8"))
        except Exception:
            continue
        resource_dir = metadata.parent
        if not (resource_dir / "fxmanifest.lua").exists():
            continue
        data["_path"] = resource_dir.relative_to(ROOT).as_posix()
        records.append(data)

records.sort(key=lambda x: (x.get("framework",""), x.get("category",""), x.get("display_name","")))

lines = [
    "# DPN FiveM Script Index",
    "",
    "This file is automatically generated from each resource's `resource.json` metadata.",
    "",
    "**DPN Technology**  ",
    "**Created by Diesel, CEO of DPN Technology**",
    "",
    "> Do not edit the generated resource table manually. Update the resource metadata instead.",
    "",
]

if not records:
    lines += [
        "## Current Catalog",
        "",
        "No production script resources have been published yet.",
        "",
        "The repository framework/category structure is ready for the first DPN release.",
        "",
    ]
else:
    current_framework = None
    current_category = None
    for item in records:
        framework = item.get("framework", "unknown")
        category = item.get("category", "uncategorized")
        if framework != current_framework:
            current_framework = framework
            current_category = None
            lines += [f"## {FRAMEWORK_LABELS.get(framework, framework.title())}", ""]
        if category != current_category:
            current_category = category
            lines += [
                f"### {category.replace('-', ' ').title()}",
                "",
                "| Resource | Version | Status | Description |",
                "|---|---:|---|---|",
            ]
        name = format_display_name(item.get("display_name", item.get("name", "Unnamed")))
        path = item["_path"]
        version = item.get("version", "—")
        status = item.get("status", "—")
        desc = str(item.get("description", "")).replace("|", "\\|").replace("\n", " ")
        lines.append(f"| [{name}]({path}/) | {version} | {status} | {desc} |")
    lines.append("")

lines += [
    "---",
    "",
    "**DPN Technology — Develop Pioneer Navigate**",
    "",
    "*We Develop what doesn't exist. We Pioneer what comes next. We Navigate the future.*",
    "",
]

(ROOT / "SCRIPT_INDEX.md").write_text("\n".join(lines), encoding="utf-8")
