const app = document.getElementById('app');
const state = { profile:null, dashboard:{}, shifts:{}, units:{}, pursuits:{}, warrants:[], forceReports:[], fleet:[], armory:[], tasks:[], recentPursuits:[], certifications:[], network:{summary:{},counts:{},resources:[],events:[],activeCalls:[],dispatchUnits:[],incidents:[],safetyAlerts:[],drones:[],bolos:[]}, config:{}, ui:{callFilter:'all',eventFilter:'active',resourceFilter:'all',query:''} };
const pageMeta = {
  dashboard:['Command Overview','Unified operational awareness across every connected DPN system.'],
  dispatch:['Dispatch & Calls','Live emergency calls, unit availability, and cross-department resource coordination.'],
  agencies:['Agency Coordination','Medical, fire, corrections, justice, administration, and infrastructure events in one timeline.'],
  network:['Systems Network','Real-time health and integration coverage for the complete DPN public-safety ecosystem.'],
  roster:['Roll Call & Units','Shift management, paired units, roles, and assignment readiness.'],
  warrants:['Warrant Registry','Request, review, approve, serve, and audit judicial process.'],
  pursuits:['Pursuit Command','Live pursuit command, tactics, authorizations, and post-event review.'],
  force:['Use-of-Force Review','Document force, connect evidence, and complete supervisory findings.'],
  fleet:['Fleet & Armory','Vehicle condition, equipment issue, certifications, and returns.'],
  supervisor:['Supervisor Queue','Prioritized administrative and operational actions requiring review.']
};

function post(name, data={}) {
  return fetch(`https://${GetParentResourceName()}/${name}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) })
    .then(r=>r.json().catch(()=>({ok:true}))).catch(()=>({ok:false}));
}
function node(tag, text='', cls='') { const e=document.createElement(tag); if(cls)e.className=cls; e.textContent=String(text??''); return e; }
function button(label, handler, cls='') { const b=node('button',label,cls); b.onclick=handler; return b; }
function values(object) { return Array.isArray(object) ? object : Object.values(object||{}); }
function jsonValue(value, fallback={}) { if(typeof value==='object' && value!==null)return value; try{return JSON.parse(value||'');}catch{return fallback;} }
function showToast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function fmtDate(value){if(!value)return 'N/A';const d=new Date(String(value).replace(' ','T'));return Number.isNaN(d.getTime())?String(value):d.toLocaleString()}
function empty(message){return node('div',message,'empty')}
function chip(text, cls=''){return node('span',text,`chip ${cls}`)}
function isSupervisor(){return !!state.profile?.supervisor}
function isJudge(){return !!state.profile?.judge}
function isLaw(){return state.profile?.department==='law'}
function myCid(){return state.profile?.citizenid}
function modal(title, build){document.getElementById('modalTitle').textContent=title;const body=document.getElementById('modalBody');body.replaceChildren();build(body);document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function field(parent, tag, placeholder, value=''){const e=document.createElement(tag);e.placeholder=placeholder||'';e.value=value??'';parent.appendChild(e);return e}
function selectField(parent, options, value){const s=document.createElement('select');Object.entries(options||{}).forEach(([key,label])=>{const o=node('option',label);o.value=key;o.selected=key===value;s.appendChild(o)});parent.appendChild(s);return s}

function metric(label,value){const m=node('div','','metric');m.append(node('span',label),node('strong',Number(value||0).toLocaleString()));return m}
function renderIdentity(){
  const p=state.profile;const network=state.network||{};const summary=network.summary||{};
  document.getElementById('identity').textContent=p?`${p.name}`:'Secure terminal';
  document.getElementById('identitySub').textContent=p?`${p.jobLabel||p.job} • Grade ${p.grade}`:'No active session';
  const badge=document.getElementById('accessBadge');badge.textContent=p?(p.onDuty?'ON DUTY':(p.judge?'JUDICIAL':'OFF DUTY')):'OFFLINE';badge.className=`badge ${(p?.onDuty||p?.judge)?'on':''}`;
  document.querySelectorAll('.supervisor-only').forEach(e=>e.style.display=(isSupervisor()||isJudge())?'':'none');
  document.querySelectorAll('.law-only').forEach(e=>e.style.display=isLaw()?'':'none');
  const critical=Number(summary.criticalOffline||0);const degraded=Number(summary.degraded||0);
  document.getElementById('networkLabel').textContent=critical?'NETWORK DEGRADED':degraded?'NETWORK PARTIAL':'NETWORK OPERATIONAL';
  document.getElementById('networkDetail').textContent=`${summary.online||0}/${summary.total||0} connected • ${summary.offline||0} offline`;
  const pill=document.querySelector('.network-pill i');if(pill)pill.style.background=critical?'var(--red)':degraded?'var(--amber)':'var(--green)';
  document.getElementById('criticalNavCount').textContent=network.counts?.criticalNetworkEvents||0;
  document.getElementById('callsNavCount').textContent=network.counts?.dispatchCalls||0;
  document.getElementById('eventsNavCount').textContent=network.counts?.openNetworkEvents||0;
  document.getElementById('offlineNavCount').textContent=summary.offline||0;
}
function renderDashboard(){
  const d=state.dashboard||{};const n=state.network||{};const nc=n.counts||{};
  const m=document.getElementById('metrics');m.replaceChildren(
    metric('Active Calls',nc.dispatchCalls??d.activeDispatchCalls),metric('On-Duty Units',nc.dispatchUnits??d.activeUnits),metric('Active Pursuits',d.activePursuits),metric('Open Incidents',nc.incidents),
    metric('Active Warrants',d.activeWarrants),metric('Evidence Cases',nc.evidenceCases),metric('Critical Alerts',nc.criticalNetworkEvents),metric('Supervisor Tasks',nc.openSupervisorTasks)
  );
  renderUnitCards(document.getElementById('dashboardUnits'), true);renderPursuitCards(document.getElementById('dashboardPursuits'), true);renderDashboardCalls();renderLauncher();renderQuickSignals();
  const cert=document.getElementById('certifications');cert.replaceChildren();const certs=values(state.certifications);if(!certs.length)cert.append(empty('No current certifications found.'));certs.slice(0,6).forEach(c=>{const r=node('div','','row');const a=node('div');a.append(node('div',c.cert_label||c.cert_id,'title'),node('div',`Score ${c.score||0} • Expires ${fmtDate(c.expires_at)}`,'meta'));r.append(a,chip(c.cert_id,'green'));cert.append(r)});
  const shift=document.getElementById('myShift');shift.replaceChildren();const ss=state.profile?.activeShift;if(!ss){shift.append(empty('No active shift. Open Roll Call & Units to begin.'));}else{[['Shift ID',ss.shiftId],['Calls',ss.calls_handled],['Citations',ss.citations],['Arrests',ss.arrests],['Searches',ss.searches],['Force Reports',ss.force_reports]].forEach(([k,v])=>{const r=node('div','','row');r.append(node('span',k),node('strong',v??0,'mono'));shift.append(r)})}
  const p=state.profile;document.getElementById('heroGreeting').textContent=p?`${p.onDuty?'Operational shift':'Command access'} • ${p.name}`:'Command center ready';
  document.getElementById('heroSummary').textContent=`${nc.dispatchCalls||0} active calls, ${nc.openNetworkEvents||0} open network events, ${d.activePursuits||0} pursuits, and ${d.pendingForceReviews||0} pending force reviews are being tracked.`;
  const summary=n.summary||{};const readiness=summary.total?Math.round((Number(summary.online||0)/Number(summary.total))*100):0;document.getElementById('readinessPercent').textContent=`${readiness}%`;document.querySelector('.readiness-ring').style.background=`conic-gradient(${readiness<70?'var(--red)':readiness<90?'var(--amber)':'var(--green)'} ${readiness*3.6}deg,rgba(255,255,255,.07) 0deg)`;document.getElementById('readinessText').textContent=summary.criticalOffline?`${summary.criticalOffline} critical system(s) offline`:summary.offline?`${summary.offline} optional system(s) offline`:'All critical systems ready';
  renderCriticalBanner();
}
function renderUnitCards(container, compact=false){
  container.replaceChildren();const units=values(state.units);if(!units.length){container.append(empty('No operational units active.'));return}
  units.forEach(u=>{const c=node('div','',compact?'row':'card');const members=values(u.members);const left=node('div');left.append(node('div',`${u.unitCode} • ${u.unitName}`,'title'),node('div',`${state.config.unitRoles?.[u.role]||u.role} • ${members.length} member(s)`,'meta'));
    if(!compact){const chips=node('div','','chips');members.forEach(m=>chips.append(chip(`${m.name} — ${m.role}`)));left.append(chips)}c.append(left);
    if(!compact && isLaw() && state.profile?.activeShift && !state.profile?.unitId)c.append(button('Join Unit',()=>post('joinUnit',{unitId:u.unitId}).then(()=>showToast(`Joining ${u.unitCode}`))));
    container.append(c)
  })
}
function renderRoster(){
  const select=document.getElementById('unitRole');select.replaceChildren();Object.entries(state.config.unitRoles||{}).forEach(([k,v])=>{const o=node('option',v);o.value=k;select.appendChild(o)});
  renderUnitCards(document.getElementById('rosterUnits'),false)
}
function warrantStatusClass(status){return status==='approved'?'green':status==='pending'?'gold':status==='denied'?'red':''}
function reviewWarrantModal(w){modal(`Review ${w.warrant_id}`,body=>{body.append(node('p',`${w.subject_name} • ${w.warrant_type}`,'hint'));const notes=field(body,'textarea','Judicial or supervisor review notes');const actions=node('div','','actions');actions.append(button('Approve',()=>post('reviewWarrant',{warrantId:w.warrant_id,decision:'approved',notes:notes.value}).then(()=>{closeModal();showToast('Warrant approved.')})),button('Deny',()=>post('reviewWarrant',{warrantId:w.warrant_id,decision:'denied',notes:notes.value}).then(()=>{closeModal();showToast('Warrant denied.')}),'danger'));body.append(actions)})}
function serveWarrantModal(w){modal(`Serve ${w.warrant_id}`,body=>{const notes=field(body,'textarea','Service details, location, property seized, arrests, or exceptions');body.append(button('Mark Warrant Served',()=>post('serveWarrant',{warrantId:w.warrant_id,notes:notes.value}).then(()=>{closeModal();showToast('Warrant marked served.')}),'danger'))})}
function revokeWarrantModal(w){modal(`Revoke ${w.warrant_id}`,body=>{const notes=field(body,'textarea','Required revocation reason');body.append(button('Revoke Warrant',()=>post('revokeWarrant',{warrantId:w.warrant_id,notes:notes.value}).then(()=>{closeModal();showToast('Warrant revoked.')}),'danger'))})}
function renderWarrants(){
  const allWarrants=values(state.warrants);document.getElementById('warrantPendingCount').textContent=allWarrants.filter(w=>w.status==='pending').length;document.getElementById('warrantApprovedCount').textContent=allWarrants.filter(w=>w.status==='approved').length;document.getElementById('warrantHighRiskCount').textContent=allWarrants.filter(w=>w.status==='approved'&&(w.risk_level==='high'||w.risk_level==='critical')).length;
  ['warrantType','warrantRisk'].forEach(id=>document.getElementById(id).replaceChildren());Object.entries(state.config.warrantTypes||{}).forEach(([k,v])=>{const o=node('option',v);o.value=k;document.getElementById('warrantType').appendChild(o)});Object.entries(state.config.warrantRisks||{}).forEach(([k,v])=>{const o=node('option',v);o.value=k;document.getElementById('warrantRisk').appendChild(o)});
  const list=document.getElementById('warrantList');list.replaceChildren();const q=document.getElementById('warrantFilter').value.toLowerCase();const warrants=values(state.warrants).filter(w=>!q||JSON.stringify(w).toLowerCase().includes(q));if(!warrants.length){list.append(empty('No warrants match this search.'));return}
  warrants.forEach(w=>{const c=node('div','','card');const head=node('div','','card-head');const a=node('div');a.append(node('div',`${w.warrant_id} • ${w.subject_name}`,'title'),node('div',`${state.config.warrantTypes?.[w.warrant_type]||w.warrant_type} • ${w.subject_type}: ${w.subject_key}`,'meta'));head.append(a,chip(String(w.status||'unknown').toUpperCase(),warrantStatusClass(w.status)));c.append(head);
    const chips=node('div','','chips');chips.append(chip(`Risk: ${w.risk_level}`,w.risk_level==='critical'?'red':''),chip(`Requested: ${w.requester_name}`),chip(`Expires: ${fmtDate(w.expires_at)}`));c.append(chips,node('div',`Charges: ${w.charges}`,'narrative'),node('div',`Probable cause: ${w.probable_cause}`,'narrative'));
    if(w.review_notes)c.append(node('div',`Review: ${w.review_notes}`,'narrative'));const actions=node('div','','actions');if(w.status==='pending'&&(isJudge()||isSupervisor()))actions.append(button('Review',()=>reviewWarrantModal(w)));if(w.status==='approved'&&isLaw())actions.append(button('Serve Warrant',()=>serveWarrantModal(w),'danger'));if((w.status==='pending'||w.status==='approved')&&(isJudge()||isSupervisor()))actions.append(button('Revoke',()=>revokeWarrantModal(w),'ghost'));c.append(actions);list.append(c)
  })
}
function pursuitMembers(p){return values(p.units)}
function pursuitTacticModal(p){modal(`Request Tactic • ${p.pursuitId}`,body=>{const tactic=selectField(body,state.config.pursuitTactics);const notes=field(body,'textarea','Tactical justification and conditions');body.append(button('Submit Request',()=>post('requestTactic',{pursuitId:p.pursuitId,tactic:tactic.value,notes:notes.value}).then(()=>{closeModal();showToast('Tactic request submitted.')})))})}
function pursuitStageModal(p){modal(`Update Stage • ${p.pursuitId}`,body=>{const stage=selectField(body,state.config.pursuitStages,p.stage);body.append(button('Update Pursuit Stage',()=>post('updatePursuit',{pursuitId:p.pursuitId,stage:stage.value}).then(()=>{closeModal();showToast('Pursuit stage updated.')})))})}
function endPursuitModal(p){modal(`Terminate ${p.pursuitId}`,body=>{const disposition=field(body,'input','Disposition: arrest, crash, escaped, voluntary stop');const notes=field(body,'textarea','Termination narrative, arrests, injuries, damage, and evidence');body.append(button('Terminate & Queue Review',()=>post('endPursuit',{pursuitId:p.pursuitId,disposition:disposition.value,notes:notes.value}).then(()=>{closeModal();showToast('Pursuit terminated.')}),'danger'))})}
function reviewTacticModal(p,key,t){modal(`Review ${state.config.pursuitTactics?.[key]||key}`,body=>{const notes=field(body,'textarea','Supervisor conditions or denial reason');const actions=node('div','','actions');actions.append(button('Authorize',()=>post('reviewTactic',{pursuitId:p.pursuitId,tactic:key,approved:true,notes:notes.value}).then(()=>{closeModal();showToast('Tactic authorized.')})),button('Deny',()=>post('reviewTactic',{pursuitId:p.pursuitId,tactic:key,approved:false,notes:notes.value}).then(()=>{closeModal();showToast('Tactic denied.')}),'danger'));body.append(actions)})}
function renderPursuitCards(container,compact=false){
  container.replaceChildren();const pursuits=values(state.pursuits);if(!pursuits.length){container.append(empty('No active pursuits.'));return}
  pursuits.forEach(p=>{const c=node('div','',compact?'row':'card priority');const members=pursuitMembers(p);const left=node('div');left.append(node('div',`${p.pursuitId} • ${p.plate}`,'title'),node('div',`${state.config.pursuitStages?.[p.stage]||p.stage} • ${Math.round(Number(p.speed||0))} MPH • Max ${Math.round(Number(p.maxSpeed||0))} MPH`,'meta'));
    if(!compact){left.append(node('div',p.reason,'narrative'));const chips=node('div','','chips');members.forEach(m=>chips.append(chip(`${m.unit||m.name} • ${m.role}`)));Object.entries(p.authorizations||{}).forEach(([k,t])=>chips.append(chip(`${state.config.pursuitTactics?.[k]||k}: ${t.status}`,t.status==='approved'?'green':t.status==='denied'?'red':'gold')));left.append(chips)}c.append(left);
    if(!compact){const actions=node('div','','actions');const mine=members.some(m=>m.citizenid===myCid()||m.source===state.profile?.source);if(!mine&&isLaw())actions.append(button('Join',()=>post('joinPursuit',{pursuitId:p.pursuitId})));actions.append(button('Waypoint',()=>post('waypointPursuit',{pursuitId:p.pursuitId})));if(mine){actions.append(button('Update Stage',()=>pursuitStageModal(p)));actions.append(button('Request Tactic',()=>pursuitTacticModal(p)));actions.append(button('Terminate',()=>endPursuitModal(p),'danger'))}if(isSupervisor())Object.entries(p.authorizations||{}).filter(([,t])=>t.status==='requested').forEach(([k,t])=>actions.append(button(`Review ${k}`,()=>reviewTacticModal(p,k,t),'ghost')));c.append(actions)}container.append(c)
  })
}
function renderPursuits(){
  const risk=document.getElementById('pursuitRisk');risk.replaceChildren();Object.entries(state.config.warrantRisks||{}).forEach(([k,v])=>{const o=node('option',v);o.value=k; risk.appendChild(o)});renderPursuitCards(document.getElementById('pursuitList'),false)
}
function editForceModal(r){modal(`Complete ${r.report_id}`,body=>{
  const level=selectField(body,state.config.forceLevels,r.force_level);const reason=field(body,'input','Reason / legal justification',r.reason||'');
  const subjectCid=field(body,'input','Subject citizen ID',r.subject_cid||'');const subjectName=field(body,'input','Subject name',r.subject_name||'');
  const weapons=field(body,'input','Weapons / tools used',r.weapons_used||'');const bodycam=field(body,'input','Bodycam reference',r.bodycam_reference||'');
  const caseRef=field(body,'input','Case reference',r.case_reference||'');const medical=field(body,'input','Medical aid provided',r.medical_aid||'');
  const injuries=field(body,'textarea','Known or reported injuries',r.injuries||'');const narrative=field(body,'textarea','Complete narrative and de-escalation efforts',r.narrative||'');
  body.append(button('Save Completed Report',()=>post('updateForceReport',{reportId:r.report_id,forceLevel:level.value,reason:reason.value,subjectCid:subjectCid.value,subjectName:subjectName.value,weaponsUsed:weapons.value,bodycamReference:bodycam.value,caseReference:caseRef.value,medicalAid:medical.value,injuries:injuries.value,narrative:narrative.value}).then(()=>{closeModal();showToast('Force report updated.')})));
})}
function forceReviewModal(r){modal(`Review ${r.report_id}`,body=>{const finding=selectField(body,state.config.reviewFindings);const notes=field(body,'textarea','Policy analysis, findings, corrective action, or investigation rationale');body.append(button('Complete Review',()=>post('reviewForceReport',{reportId:r.report_id,finding:finding.value,notes:notes.value}).then(()=>{closeModal();showToast('Force review completed.')})))})}
function renderForce(){
  const level=document.getElementById('forceLevel');level.replaceChildren();Object.entries(state.config.forceLevels||{}).forEach(([k,v])=>{const o=node('option',v);o.value=k;level.appendChild(o)});
  const list=document.getElementById('forceList');list.replaceChildren();const reports=values(state.forceReports);if(!reports.length){list.append(empty('No force reports available.'));return}reports.forEach(r=>{const c=node('div','',`card ${r.force_level==='lethal'?'priority':''}`);const head=node('div','','card-head');const a=node('div');a.append(node('div',`${r.report_id} • ${r.officer_name}`,'title'),node('div',`${state.config.forceLevels?.[r.force_level]||r.force_level} • ${fmtDate(r.created_at)}`,'meta'));head.append(a,chip(String(r.status||'pending').toUpperCase(),r.status==='reviewed'?'green':'gold'));c.append(head);
    const chips=node('div','','chips');if(Number(r.automatic_draft)===1)chips.append(chip('AUTOMATIC DRAFT','red'));if(r.subject_name)chips.append(chip(`Subject: ${r.subject_name}`));if(r.bodycam_reference)chips.append(chip(`Bodycam: ${r.bodycam_reference}`));c.append(chips,node('div',`Reason: ${r.reason}`,'narrative'),node('div',r.narrative||'No narrative entered.','narrative'));if(r.review_finding)c.append(node('div',`Finding: ${state.config.reviewFindings?.[r.review_finding]||r.review_finding} — ${r.review_notes||''}`,'narrative'));const actions=node('div','','actions');if(r.status==='pending'&&r.officer_cid===myCid())actions.append(button(Number(r.automatic_draft)===1?'Complete Draft':'Edit Report',()=>editForceModal(r)));if(r.status==='pending'&&isSupervisor())actions.append(button('Supervisor Review',()=>forceReviewModal(r)));if(actions.children.length)c.append(actions);list.append(c)})
}
function renderFleet(){
  const catalog=document.getElementById('armoryCatalog');catalog.replaceChildren();Object.entries(state.config.armoryCatalog||{}).forEach(([k,v])=>{const o=node('option',`${v.label}${v.cert?` • requires ${v.cert}`:''}`);o.value=k;catalog.appendChild(o)});
  const fleet=document.getElementById('fleetList');fleet.replaceChildren();const rows=values(state.fleet);if(!rows.length)fleet.append(empty('No active fleet checkouts.'));rows.forEach(r=>{const c=node('div','','card');c.append(node('div',`${r.vehicle_plate} • ${r.checkout_id}`,'title'),node('div',`${r.officer_name} • Checked out ${fmtDate(r.checked_out_at)}`,'meta'));const actions=node('div','','actions');if(r.officer_cid===myCid()||isSupervisor())actions.append(button('Return Vehicle',()=>post('returnVehicle',{checkoutId:r.checkout_id,damageNotes:document.getElementById('fleetDamageNotes').value}).then(()=>showToast('Vehicle return submitted.')),'danger'));c.append(actions);fleet.append(c)});
  const armory=document.getElementById('armoryList');armory.replaceChildren();const items=values(state.armory);if(!items.length)armory.append(empty('No active armory assignments.'));items.forEach(r=>{const c=node('div','','card');c.append(node('div',`${r.item_label} × ${r.quantity}`,'title'),node('div',`${r.officer_name} • ${r.checkout_id} • Serial ${r.serial_number||'N/A'}`,'meta'));const actions=node('div','','actions');if(r.officer_cid===myCid()||isSupervisor())actions.append(button('Return Equipment',()=>post('returnArmory',{checkoutId:r.checkout_id}).then(()=>showToast('Equipment return submitted.')),'danger'));c.append(actions);armory.append(c)})
}
function pursuitReviewModal(p){modal(`Review ${p.pursuit_id}`,body=>{const finding=selectField(body,state.config.pursuitReviewFindings,p.review_finding||'within_policy');const notes=field(body,'textarea','Policy analysis, tactics, supervision, damage, injuries, and corrective action',p.review_notes||'');body.append(button('Complete Pursuit Review',()=>post('reviewPursuit',{pursuitId:p.pursuit_id,finding:finding.value,notes:notes.value}).then(()=>{closeModal();showToast('Pursuit review completed.')})))})}
function renderTasks(){
  const list=document.getElementById('taskList');list.replaceChildren();const tasks=values(state.tasks);if(!tasks.length)list.append(empty('No open supervisor tasks.'));tasks.forEach(t=>{const c=node('div','',`card ${Number(t.priority)===1?'priority':''}`);c.append(node('div',`${t.task_id} • ${t.title}`,'title'),node('div',`${t.task_type} • Priority ${t.priority} • Ref ${t.reference_id} • ${fmtDate(t.created_at)}`,'meta'));const actions=node('div','','actions');actions.append(button('Mark Complete',()=>post('completeTask',{taskId:t.task_id}).then(()=>showToast('Task completed.'))));c.append(actions);list.append(c)});
  const recent=document.getElementById('recentPursuitList');recent.replaceChildren();const pursuits=values(state.recentPursuits);if(!pursuits.length)recent.append(empty('No closed pursuits available.'));pursuits.forEach(p=>{const c=node('div','','card');c.append(node('div',`${p.pursuit_id} • ${p.vehicle_plate}`,'title'),node('div',`${p.primary_name} • ${p.disposition||'No disposition'} • Max ${Math.round(Number(p.max_speed||0))} MPH • ${fmtDate(p.ended_at)}`,'meta'),node('div',p.termination_notes||'No termination narrative.','narrative'));const chips=node('div','','chips');chips.append(chip(String(p.review_status||'pending').toUpperCase(),p.review_status==='reviewed'?'green':'gold'));if(p.review_finding)chips.append(chip(state.config.pursuitReviewFindings?.[p.review_finding]||p.review_finding));c.append(chips);if(p.review_status!=='reviewed')c.append(button('Complete Review',()=>pursuitReviewModal(p)));recent.append(c)})
}

function normalizedCalls(){return values(state.network?.activeCalls).sort((a,b)=>Number(a.priority||5)-Number(b.priority||5))}
function callId(c){return c.callId||c.call_id||c.id||'CALL'}
function callTitle(c){return c.title||c.code||c.callType||c.call_type||'Emergency Call'}
function callDescription(c){return c.description||c.message||c.notes||'No description available.'}
function callDepartment(c){const d=c.departments||c.department||c.agency||'';return typeof d==='object'?JSON.stringify(d):String(d)}
function renderDashboardCalls(){const list=document.getElementById('dashboardCalls');list.replaceChildren();const calls=normalizedCalls().slice(0,6);if(!calls.length){list.append(empty('No active dispatch calls.'));return}calls.forEach(c=>{const item=node('div','','timeline-item');const p=Number(c.priority||3);item.append(node('div',`P${p}`,`priority-token p${p}`));const body=node('div');body.append(node('h4',`${c.code||'CALL'} • ${callTitle(c)}`),node('p',`${callDescription(c)} • ${callDepartment(c)||'multi-agency'}`));item.append(body,node('span',callId(c),'time'));list.append(item)})}
function renderLauncher(){const box=document.getElementById('moduleLauncher');box.replaceChildren();const modules=state.config?.moduleLauncher||{};const logical={dispatch:'dispatch',mdt:'mdt',core:'law_core',vehicle:'vehicle_computer',evidence:'evidence',intelligence:'intelligence',incident:'incident_command',safety:'officer_safety',smartcity:'smart_city',drone:'drone',academy:'training',medical:'medical',fire:'fire',corrections:'corrections',justice:'justice',mib:'mib',starchase:'starchase',bodycam:'bodycam'};Object.entries(modules).slice(0,10).forEach(([key,m])=>{const online=agencySystem(logical[key])?.state==='started'||!m.resource;const b=button(`${online?'●':'○'} ${m.label}`,()=>post('launchModule',{module:key}).then(r=>!r.ok&&showToast(`Unable to open ${m.label}.`)),online?'':'ghost');b.title=online?'Open connected module':'Resource is not currently detected';box.append(b)})}
function renderQuickSignals(){const box=document.getElementById('quickSignals');box.replaceChildren();Object.entries(state.config?.networkQuickSignals||{}).slice(0,4).forEach(([key,sig])=>box.append(button(sig.label,()=>networkSignalModal(key,sig),sig.severity===1?'danger':'')));const agency=document.getElementById('agencyQuickActions');agency.replaceChildren();Object.entries(state.config?.networkQuickSignals||{}).forEach(([key,sig])=>agency.append(button(sig.label,()=>networkSignalModal(key,sig),sig.severity===1?'danger':'')))}
function networkSignalModal(key,sig){modal(sig.label,body=>{body.append(node('p','This creates a verified cross-agency event and routes it through DPN dispatch according to network policy.','hint'));const message=field(body,'textarea','Add operational details, threat information, patient condition, or requested resources');const reference=field(body,'input','Optional case, incident, patient, or transport reference');body.append(button('Transmit Secure Request',()=>post('networkSignal',{signal:key,message:message.value,reference:reference.value}).then(()=>{closeModal();showToast(`${sig.label} transmitted.`)}),sig.severity===1?'danger':''))})}
function renderCriticalBanner(){const events=values(state.network?.events).filter(e=>Number(e.severity)===1&&(e.status==='open'||e.status==='acknowledged'));const banner=document.getElementById('criticalBanner');banner.classList.toggle('hidden',!events.length);if(events.length)document.getElementById('criticalBannerText').textContent=`${events[0].title} • ${events[0].message||'Immediate coordination required.'}`}
function filteredCalls(){const f=state.ui.callFilter||'all';const q=state.ui.query||'';return normalizedCalls().filter(c=>{const text=JSON.stringify(c).toLowerCase();if(q&&!text.includes(q))return false;if(f==='all')return true;if(f==='1')return Number(c.priority)===1;return callDepartment(c).toLowerCase().includes(f)})}
function renderDispatch(){const calls=filteredCalls();document.getElementById('activeCallCount').textContent=`${calls.length} ACTIVE`;document.getElementById('dispatchUpdated').textContent=`Updated ${new Date((state.network?.generatedAt||Date.now()/1000)*1000).toLocaleTimeString()}`;const list=document.getElementById('dispatchCallList');list.replaceChildren();if(!calls.length)list.append(empty('No dispatch calls match the current filter.'));calls.forEach(c=>{const card=node('div','','card call-card');const p=Number(c.priority||3);card.append(node('div',c.code||`P${p}`,`call-code ${p===1?'p1':''}`));const body=node('div');body.append(node('div',`${callTitle(c)} • ${callId(c)}`,'title'),node('div',`${callDescription(c)} • ${callDepartment(c)||'multi-agency'}`,'meta'));const chips=node('div','','chips');chips.append(chip(`P${p}`,p===1?'red':p===2?'gold':''),chip(String(c.status||'active').toUpperCase()),chip(`${values(c.units||c.assignedUnits).length} unit(s)`));body.append(chips);card.append(body);const actions=node('div','','actions');if(c.coords)actions.append(button('Waypoint',()=>post('networkWaypoint',{coords:c.coords}),'ghost'));card.append(actions);list.append(card)});
 const units=document.getElementById('dispatchUnitList');units.replaceChildren();const rows=values(state.network?.dispatchUnits);if(!rows.length)units.append(empty('No dispatch units are reporting.'));rows.forEach(u=>{const line=node('div','','unit-line');line.append(node('i'));const body=node('div');body.append(node('strong',u.unit||u.callsign||u.name||`Unit ${u.source||''}`),node('span',`${u.name||u.officerName||u.job||'Emergency unit'} • ${u.status||'available'}`));line.append(body,node('em',u.department||u.job||''));units.append(line)})}
function agencySystem(logical){return values(state.network?.resources).find(r=>r.logical===logical)}
function renderAgencies(){const systems=[['law_core','Law Enforcement'],['medical','Medical'],['fire','Fire & Rescue'],['corrections','Corrections'],['justice','Justice'],['dispatch','Dispatch'],['mdt','MDT / Records'],['mib','MIB Admin'],['traffic','Infrastructure'],['mechanic','Fleet Support']];const grid=document.getElementById('agencyStatusGrid');grid.replaceChildren();systems.forEach(([key,label])=>{const r=agencySystem(key)||{};const tile=node('div','','agency-tile');const head=node('div');head.append(node('strong',label),node('i','',`status-dot ${r.state==='started'?'online':'offline'}`));tile.append(head,node('p',r.state==='started'?`${r.resource} connected`:`${r.resource||'No resource detected'} • ${r.state||'offline'}`));grid.append(tile)});renderNetworkEvents()}
function networkEventModal(e){modal(`${e.event_id} • ${e.title}`,body=>{body.append(node('p',`${e.source_system} / ${e.event_type} • Priority ${e.severity} • ${fmtDate(e.created_at)}`,'hint'),node('div',e.message||'No event narrative.','narrative'));const refs=node('div','','chips');if(e.dispatch_call_id)refs.append(chip(`Dispatch ${e.dispatch_call_id}`));if(e.incident_id)refs.append(chip(`Incident ${e.incident_id}`));if(e.evidence_reference)refs.append(chip(`Evidence ${e.evidence_reference}`));body.append(refs);const actions=node('div','','actions');if(e.coords)actions.append(button('Set Waypoint',()=>post('networkWaypoint',{coords:e.coords}).then(()=>showToast('Waypoint set.')),'ghost'));if(e.status==='open')actions.append(button('Acknowledge',()=>post('acknowledgeNetworkEvent',{eventId:e.event_id}).then(()=>{closeModal();showToast('Event acknowledged.')})));if(e.status==='open'||e.status==='acknowledged')actions.append(button('Resolve Event',()=>resolveNetworkModal(e),'danger'));body.append(actions)})}
function resolveNetworkModal(e){modal(`Resolve ${e.event_id}`,body=>{const resolution=field(body,'textarea','Resolution, disposition, transferred responsibility, or follow-up required');body.append(button('Close Network Event',()=>post('resolveNetworkEvent',{eventId:e.event_id,resolution:resolution.value}).then(()=>{closeModal();showToast('Event resolution submitted.')}),'danger'))})}
function filteredEvents(){const f=state.ui.eventFilter||'active';const q=state.ui.query||'';return values(state.network?.events).filter(e=>{const text=JSON.stringify(e).toLowerCase();if(q&&!text.includes(q))return false;if(f==='all')return true;if(f==='critical')return Number(e.severity)===1;return e.status==='open'||e.status==='acknowledged'})}
function renderNetworkEvents(){const list=document.getElementById('networkEventList');list.replaceChildren();const events=filteredEvents();if(!events.length){list.append(empty('No network events match this filter.'));return}events.forEach(e=>{const card=node('div','',`event-card severity-${e.severity}`);const head=node('div','','event-head');head.append(node('strong',`${e.title} • ${e.event_id}`),node('span',fmtDate(e.created_at)));card.append(head,node('p',e.message||'No event details.'));const chips=node('div','','chips');chips.append(chip(String(e.source_system||'system').toUpperCase()),chip(`P${e.severity}`,Number(e.severity)===1?'red':Number(e.severity)===2?'gold':''),chip(String(e.status||'open').toUpperCase(),e.status==='resolved'?'green':''));if(e.dispatch_call_id)chips.append(chip(`CALL ${e.dispatch_call_id}`));card.append(chips);card.onclick=()=>networkEventModal(e);list.append(card)})}
function renderNetwork(){const summary=state.network?.summary||{};const counts=state.network?.counts||{};const cards=document.getElementById('networkSummaryCards');cards.replaceChildren();[['Online',summary.online],['Degraded',summary.degraded],['Offline',summary.offline],['Critical Offline',summary.criticalOffline],['Open Events',counts.openNetworkEvents]].forEach(([l,v])=>{const d=node('div');d.append(node('strong',v||0),node('span',l));cards.append(d)});const filter=state.ui.resourceFilter||'all';const q=state.ui.query||'';const resources=values(state.network?.resources).filter(r=>{if(q&&!JSON.stringify(r).toLowerCase().includes(q))return false;if(filter==='all')return true;if(filter==='offline')return r.state!=='started';return r.category===filter});const matrix=document.getElementById('resourceMatrix');matrix.replaceChildren();resources.forEach(r=>{const c=node('div','','resource-card');const h=node('div','','resource-head');h.append(node('strong',r.label||r.logical),node('span',String(r.state||'missing').toUpperCase(),`resource-state ${r.state==='started'?'':'offline'}`));c.append(h,node('p',`${r.resource||'No alias found'} • ${r.category||'uncategorized'}${r.critical?' • CRITICAL':''}`));matrix.append(c)});if(!resources.length)matrix.append(empty('No resources match this filter.'));const caps=document.getElementById('capabilityList');caps.replaceChildren();const groups={Core:['law_core','law_operations','dispatch','emergency_network'],Records:['mdt','evidence','intelligence','justice'],Field:['officer_safety','vehicle_computer','starchase','bodycam','drone'],Agencies:['medical','fire','corrections','mib'],Infrastructure:['smart_city','traffic','mechanic','queue']};Object.entries(groups).forEach(([label,keys])=>{const online=keys.filter(k=>agencySystem(k)?.state==='started').length;const pct=Math.round(online/keys.length*100);const c=node('div','','capability');c.append(node('strong',label),node('span',`${online}/${keys.length} integrations online`));const bar=node('div','','bar');const i=node('i');i.style.width=`${pct}%`;bar.append(i);c.append(bar);caps.append(c)})}
function renderSupervisorMetrics(){const box=document.getElementById('supervisorMetrics');box.replaceChildren();const d=state.dashboard||{};[['Open Tasks',values(state.tasks).length],['Pending Warrants',d.pendingWarrants],['Force Reviews',d.pendingForceReviews],['Fleet Assignments',d.activeFleet],['Critical Events',state.network?.counts?.criticalNetworkEvents]].forEach(([l,v])=>{const x=node('div');x.append(node('strong',v||0),node('span',l));box.append(x)})}
function updateClock(){const now=new Date();document.getElementById('liveClock').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});document.getElementById('liveDate').textContent=now.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}
function openTab(id){const nav=document.querySelector(`.nav[data-tab="${id}"]`);if(!nav)return;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===nav));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));const meta=pageMeta[id]||[id,''];document.getElementById('pageTitle').textContent=meta[0];document.getElementById('pageSubtitle').textContent=meta[1]}
function renderAll(){renderIdentity();renderDashboard();renderDispatch();renderAgencies();renderRoster();renderWarrants();renderPursuits();renderForce();renderFleet();renderNetwork();renderTasks();renderSupervisorMetrics()}


window.addEventListener('message',event=>{const data=event.data||{};if(data.action==='open')app.classList.remove('hidden');if(data.action==='close')app.classList.add('hidden');if(data.action==='sync'){Object.assign(state,data.state||{});renderAll()}});
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>openTab(n.dataset.tab));document.querySelectorAll('[data-open-tab]').forEach(b=>b.onclick=()=>openTab(b.dataset.openTab));
document.getElementById('close').onclick=()=>post('close');document.getElementById('refresh').onclick=()=>post('refresh').then(()=>showToast('Refreshing operations data.'));document.getElementById('modalClose').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!document.getElementById('modal').classList.contains('hidden'))closeModal();else post('close')}});
document.getElementById('startShift').onclick=()=>post('startShift',{notes:document.getElementById('shiftNotes').value}).then(()=>showToast('Starting shift.'));document.getElementById('endShift').onclick=()=>post('endShift',{notes:document.getElementById('shiftNotes').value,reason:'completed'}).then(()=>showToast('Ending shift.'));
document.getElementById('createUnit').onclick=()=>post('createUnit',{unitCode:document.getElementById('unitCode').value,unitName:document.getElementById('unitName').value,role:document.getElementById('unitRole').value}).then(()=>showToast('Creating operational unit.'));document.getElementById('leaveUnit').onclick=()=>post('leaveUnit').then(()=>showToast('Leaving operational unit.'));
document.getElementById('requestWarrant').onclick=()=>post('requestWarrant',{warrantType:document.getElementById('warrantType').value,subjectType:document.getElementById('warrantSubjectType').value,subjectKey:document.getElementById('warrantSubjectKey').value,subjectName:document.getElementById('warrantSubjectName').value,riskLevel:document.getElementById('warrantRisk').value,expiryDays:document.getElementById('warrantExpiry').value,charges:document.getElementById('warrantCharges').value,probableCause:document.getElementById('warrantCause').value}).then(()=>showToast('Warrant submitted.'));document.getElementById('warrantFilter').oninput=renderWarrants;
document.getElementById('startPursuit').onclick=()=>post('startPursuit',{riskLevel:document.getElementById('pursuitRisk').value,reason:document.getElementById('pursuitReason').value}).then(r=>r.ok&&showToast('Vehicle acquisition submitted.'));
document.getElementById('submitForce').onclick=()=>post('createForceReport',{forceLevel:document.getElementById('forceLevel').value,reason:document.getElementById('forceReason').value,subjectCid:document.getElementById('forceSubjectCid').value,subjectName:document.getElementById('forceSubjectName').value,weaponsUsed:document.getElementById('forceWeapons').value,bodycamReference:document.getElementById('forceBodycam').value,caseReference:document.getElementById('forceCase').value,medicalAid:document.getElementById('forceMedical').value,injuries:document.getElementById('forceInjuries').value,narrative:document.getElementById('forceNarrative').value}).then(()=>showToast('Use-of-force report submitted.'));
document.getElementById('checkoutVehicle').onclick=()=>post('checkoutVehicle').then(r=>r.ok&&showToast('Fleet checkout submitted.'));document.getElementById('checkoutArmory').onclick=()=>post('checkoutArmory',{catalogId:document.getElementById('armoryCatalog').value,quantity:document.getElementById('armoryQuantity').value,serialNumber:document.getElementById('armorySerial').value}).then(()=>showToast('Armory issue submitted.'));

document.querySelectorAll('[data-call-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-call-filter]').forEach(x=>x.classList.toggle('active',x===b));state.ui.callFilter=b.dataset.callFilter;renderDispatch()});
document.querySelectorAll('[data-event-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-event-filter]').forEach(x=>x.classList.toggle('active',x===b));state.ui.eventFilter=b.dataset.eventFilter;renderNetworkEvents()});
document.querySelectorAll('[data-resource-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-resource-filter]').forEach(x=>x.classList.toggle('active',x===b));state.ui.resourceFilter=b.dataset.resourceFilter;renderNetwork()});
document.getElementById('globalSearch').oninput=e=>{state.ui.query=String(e.target.value||'').trim().toLowerCase();renderDispatch();renderNetworkEvents();renderNetwork()};
document.getElementById('linkRecords').onclick=()=>post('linkNetworkRecords',{leftSystem:'law_enforcement',leftType:'record',leftId:document.getElementById('linkLeftId').value,rightSystem:'dpn_network',rightType:'record',rightId:document.getElementById('linkRightId').value,relationship:document.getElementById('linkRelationship').value}).then(()=>showToast('Cross-system link submitted.'));
updateClock();setInterval(updateClock,1000);
